-- Tracked ATS boards (source of truth for ingest / discover). Seeded from former config/companies.ts.

CREATE TABLE IF NOT EXISTS tracked_boards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  source text NOT NULL CHECK (source IN ('greenhouse', 'lever', 'ashby', 'oracle', 'smartrecruiters')),
  board_token text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  discovery_method text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source, board_token)
);

CREATE INDEX IF NOT EXISTS tracked_boards_active_idx
  ON tracked_boards (active)
  WHERE active;

INSERT INTO tracked_boards (name, source, board_token)
VALUES
  ('1-800 Contacts', 'greenhouse', '1800contacts'),
  ('10a Labs', 'greenhouse', '10alabs'),
  ('10Beauty', 'greenhouse', '10beauty'),
  ('60decibelsinc', 'greenhouse', '60decibelsinc'),
  ('A Thinking Ape', 'greenhouse', 'athinkingape'),
  ('Abacus Insights', 'greenhouse', 'abacusinsights'),
  ('AbelsonTaylor', 'greenhouse', 'abelsontaylor'),
  ('AccuWeather', 'greenhouse', 'accuweather'),
  ('ACLU Kentucky', 'greenhouse', 'acluinternships'),
  ('Ad Council', 'greenhouse', 'adcouncil'),
  ('Ada', 'greenhouse', 'ada18'),
  ('Advanced Space', 'greenhouse', 'advancedspace'),
  ('Aevex Aerospace', 'greenhouse', 'aevexaerospace'),
  ('Affirm', 'greenhouse', 'affirm'),
  ('AgWest Farm Credit', 'greenhouse', 'agwestfarmcredit'),
  ('Airbnb', 'greenhouse', 'airbnb'),
  ('AirCapture', 'greenhouse', 'aircapture'),
  ('Alamar Biosciences', 'greenhouse', 'alamarbiosciences'),
  ('Alarm.com', 'greenhouse', 'alarmcom'),
  ('ALKU', 'greenhouse', 'alku'),
  ('Alo Yoga', 'greenhouse', 'aloyoga'),
  ('AMAROK Security', 'greenhouse', 'amarok'),
  ('American Institutes for Research', 'greenhouse', 'americaninstitutesforresearch'),
  ('Amp Robotics', 'greenhouse', 'ampsortation'),
  ('Anduril', 'greenhouse', 'andurilindustries'),
  ('Anthropic', 'greenhouse', 'anthropic'),
  ('Antora Energy', 'greenhouse', 'antora'),
  ('Apera AI', 'greenhouse', 'aperaaiinc'),
  ('Apex Companies', 'greenhouse', 'apexcompanies'),
  ('Appian', 'greenhouse', 'appian'),
  ('Apptronik', 'greenhouse', 'apptronik'),
  ('Aquatic Capital Management', 'greenhouse', 'aquaticcapitalmanagement'),
  ('Arcesium', 'greenhouse', 'arcesiumllc'),
  ('Archer', 'greenhouse', 'archer56'),
  ('Arevon', 'greenhouse', 'arevonenergyimpltest'),
  ('Argmax', 'greenhouse', 'argmax'),
  ('Armada', 'greenhouse', 'armada'),
  ('Arvinas', 'greenhouse', 'arvinas'),
  ('Asana', 'greenhouse', 'asana'),
  ('Assured Guaranty', 'greenhouse', 'assuredguaranty'),
  ('Astera Labs', 'greenhouse', 'asteraearlycareer2026'),
  ('Astera Labs', 'greenhouse', 'asteralabs'),
  ('Astranis', 'greenhouse', 'astranis'),
  ('Atlas Energy Solutions', 'greenhouse', 'atlassand'),
  ('Atoms', 'greenhouse', 'cssmerge'),
  ('Attentive', 'greenhouse', 'attentive'),
  ('Auctane', 'greenhouse', 'auctane'),
  ('Audax Group', 'greenhouse', 'audaxgroup'),
  ('Authentic', 'greenhouse', 'authenticbrandsgroup'),
  ('AvePoint', 'greenhouse', 'avepoint'),
  ('Avride', 'greenhouse', 'avride'),
  ('Axiomatic AI', 'greenhouse', 'axiomaticai'),
  ('Axios', 'greenhouse', 'axios'),
  ('Axon', 'greenhouse', 'axon'),
  ('Axon', 'greenhouse', 'axontalentcommunity'),
  ('AXQ Capital', 'greenhouse', 'axq'),
  ('AXS', 'greenhouse', 'axs'),
  ('Axsome Therapeutics Inc', 'greenhouse', 'axsometherapeutics'),
  ('Aypa Power', 'greenhouse', 'aypapower'),
  ('Babel Street', 'greenhouse', 'babelstreet'),
  ('BambooHR', 'greenhouse', 'bamboohr17'),
  ('Bandwidth', 'greenhouse', 'bandwidth'),
  ('BCG', 'greenhouse', 'bcg'),
  ('BetterHelp', 'greenhouse', 'betterhelpcom'),
  ('BillionToOne', 'greenhouse', 'billiontoone'),
  ('BlackEdge Capital', 'greenhouse', 'blackedgecapital'),
  ('BlackSky', 'greenhouse', 'blacksky'),
  ('Block', 'greenhouse', 'block'),
  ('Blockchain.com', 'greenhouse', 'blockchain'),
  ('Bloomberg Philanthropies', 'greenhouse', 'bloombergdotorg'),
  ('Blue Sky Innovators', 'greenhouse', 'blueskyinnovators'),
  ('BlueLabs Analytics', 'greenhouse', 'bluelabsanalyticsinc'),
  ('Bluestaq', 'greenhouse', 'bluestaq'),
  ('Bot Auto', 'greenhouse', 'botauto'),
  ('Box', 'greenhouse', 'boxinc'),
  ('Bracebridge Capital', 'greenhouse', 'bracebridgecapital'),
  ('Breeze Airways', 'greenhouse', 'breezeairways'),
  ('Brevium', 'greenhouse', 'brevium'),
  ('BrightAI', 'greenhouse', 'brightai'),
  ('BTI360', 'greenhouse', 'bti36021'),
  ('Bugcrowd', 'greenhouse', 'bugcrowd'),
  ('Businessolver', 'greenhouse', 'businessolverinvitationonly'),
  ('Calyxo', 'greenhouse', 'calyxo'),
  ('Cambridge Mobile Telematics', 'greenhouse', 'cmt'),
  ('Cartesian', 'greenhouse', 'cartesiansystems'),
  ('Cell Signaling Technology', 'greenhouse', 'cellsignalingtechnology79'),
  ('Celonis', 'greenhouse', 'celonis'),
  ('Checkr', 'greenhouse', 'checkr'),
  ('Chicago Trading Company', 'greenhouse', 'chicagotradingcampus'),
  ('Chicago Trading Company', 'greenhouse', 'ctccampusboard'),
  ('Clarity Innovations', 'greenhouse', 'clarityinnovates'),
  ('CLEAR', 'greenhouse', 'clear'),
  ('Clearway Energy', 'greenhouse', 'clearwayjobs'),
  ('Climate Corps', 'greenhouse', 'cc'),
  ('Clockwork Systems', 'greenhouse', 'clockworksystems'),
  ('Cloudflare', 'greenhouse', 'cloudflare'),
  ('CloudKitchens', 'greenhouse', 'css'),
  ('Cobalt', 'greenhouse', 'cobaltio'),
  ('Cognitiv', 'greenhouse', 'cognitiv'),
  ('Cohere Health', 'greenhouse', 'coherehealth'),
  ('Coinbase', 'greenhouse', 'coinbase'),
  ('CoLab Software', 'greenhouse', 'colabsoftware'),
  ('Commvault', 'greenhouse', 'commvault'),
  ('Compeer Financial', 'greenhouse', 'compeerfinancial'),
  ('Comstock Companies', 'greenhouse', 'comstock'),
  ('Concentric', 'greenhouse', 'concentric'),
  ('Conner Strong & Buckelew', 'greenhouse', 'connerstrongbuckelew'),
  ('Constant Contact', 'greenhouse', 'constantcontact'),
  ('Construction Resources', 'greenhouse', 'constructionresources'),
  ('Correlation One', 'greenhouse', 'correlationone'),
  ('Correlation One', 'greenhouse', 'expertnetwork'),
  ('Cortland', 'greenhouse', 'cortland'),
  ('Cresta', 'greenhouse', 'cresta'),
  ('Critical Mass', 'greenhouse', 'criticalmass'),
  ('Custom Computer Specialists', 'greenhouse', 'customcomputerspecialists'),
  ('Dark Wolf Solutions', 'greenhouse', 'darkwolfsolutions'),
  ('Databricks', 'greenhouse', 'databricks'),
  ('DC Water', 'oracle', 'elxb.fa.us2.oraclecloud.com|CX'),
  ('Defense Unicorns', 'greenhouse', 'defenseunicorns'),
  ('DESIGNME Hair', 'greenhouse', 'designmehair'),
  ('Detroit Lions', 'greenhouse', 'detroitlions'),
  ('DevRev', 'greenhouse', 'devrev'),
  ('DH Pace', 'greenhouse', 'dhpace'),
  ('DiDi Global', 'greenhouse', 'didi'),
  ('Digs', 'greenhouse', 'digs'),
  ('Diligent Corporation', 'greenhouse', 'diligentcorporation'),
  ('Discord', 'greenhouse', 'discord'),
  ('Disney', 'greenhouse', 'disney'),
  ('Doctors Without Borders', 'greenhouse', 'msfcareers'),
  ('Docugami', 'greenhouse', 'docugami'),
  ('DoorDash', 'greenhouse', 'doordashusa'),
  ('Dorsia', 'greenhouse', 'dorsia'),
  ('Double Good', 'greenhouse', 'doublegood'),
  ('DoubleVerify', 'greenhouse', 'doubleverify'),
  ('Doximity', 'greenhouse', 'doximity'),
  ('DriveWealth', 'greenhouse', 'drivewealth'),
  ('Dropbox', 'greenhouse', 'dropbox'),
  ('DRW', 'greenhouse', 'drweng'),
  ('DRW', 'greenhouse', 'drwuniversityjobs'),
  ('DV Trading', 'greenhouse', 'dvtrading'),
  ('EarnIn', 'greenhouse', 'earnin'),
  ('Echodyne', 'greenhouse', 'echodynecorp'),
  ('edmentum', 'greenhouse', 'edmentum'),
  ('Efficient Computer', 'greenhouse', 'efficientcomputer'),
  ('Eikon Therapeutics', 'greenhouse', 'eikontherapeutics'),
  ('Elastic', 'greenhouse', 'elastic'),
  ('Elevations Credit Union', 'greenhouse', 'elevationscreditunion'),
  ('EnergyHub', 'greenhouse', 'energyhub'),
  ('Eudia', 'greenhouse', 'eudia'),
  ('Eulerity', 'greenhouse', 'eulerity'),
  ('Everlaw', 'greenhouse', 'everlaw'),
  ('Evolver', 'greenhouse', 'evolver'),
  ('Excel Sports Management', 'greenhouse', 'excelsportsmanagement'),
  ('ExodusPoint', 'greenhouse', 'exoduspoint'),
  ('ezCater', 'greenhouse', 'ezcaterinc'),
  ('F. Schumacher & Co.', 'greenhouse', 'fschumacherco'),
  ('Faire', 'greenhouse', 'faire'),
  ('Fairlife', 'greenhouse', 'fairlife'),
  ('Fever Up', 'greenhouse', 'feverup'),
  ('Figma', 'greenhouse', 'figma'),
  ('Figure', 'greenhouse', 'figure'),
  ('Figure', 'greenhouse', 'figureai'),
  ('Financial Technology Partners', 'greenhouse', 'financialtechnologypartners'),
  ('Five Rings Capital', 'greenhouse', 'fiveringsllc'),
  ('Flagship Pioneering', 'greenhouse', 'flagshippioneeringinc'),
  ('Flagship Pioneering', 'greenhouse', 'fspco-op012325'),
  ('Flow Traders', 'greenhouse', 'flowtraders'),
  ('Focus Financial Partners', 'greenhouse', 'focusfinancialpartners'),
  ('Foley Hoag', 'greenhouse', 'foleyhoag'),
  ('Formic', 'greenhouse', 'formic'),
  ('Fortera', 'greenhouse', 'forteracorporation'),
  ('Forward Networks', 'greenhouse', 'forwardnetworks'),
  ('Four Hands', 'greenhouse', 'fourhands'),
  ('FourKites', 'greenhouse', 'fourkites'),
  ('Freeform', 'greenhouse', 'freeformfuturecorp'),
  ('Fussball Club Cincinnati LLC (“FC Cincinnati”)', 'greenhouse', 'fccincinnati'),
  ('Galaxy', 'greenhouse', 'galaxydigitalservices'),
  ('Gametime', 'greenhouse', 'gametimeunited'),
  ('Garda Capital Partners', 'greenhouse', 'gardacp'),
  ('GCM Grosvenor', 'greenhouse', 'gcmgrosvenor'),
  ('Gelber Group', 'greenhouse', 'gelbergroup'),
  ('Gelber Group', 'greenhouse', 'gelberhandshake'),
  ('Gemini', 'greenhouse', 'gemini'),
  ('General Atlantic', 'greenhouse', 'generalatlantic'),
  ('General Matter', 'greenhouse', 'generalmatter'),
  ('Geneva Trading', 'greenhouse', 'genevatrading'),
  ('GenScript', 'greenhouse', 'genscript'),
  ('Gensyn', 'greenhouse', 'gensyn'),
  ('Geotab', 'greenhouse', 'geotab'),
  ('Ginkgo Bioworks', 'greenhouse', 'ginkgobioworks'),
  ('Globalization Partners', 'greenhouse', 'globalizationpartners'),
  ('GlossGenius', 'greenhouse', 'glossgenius'),
  ('Glydways', 'greenhouse', 'glydways'),
  ('GoDaddy', 'greenhouse', 'eventsandinterns'),
  ('GoFundMe', 'greenhouse', 'gofundme'),
  ('Golden Pet Brands', 'greenhouse', 'goldenpetbrands'),
  ('Graphcore', 'greenhouse', 'graphcore'),
  ('Grassroots Analytics', 'greenhouse', 'grassrootsanalytics'),
  ('Greenworks', 'greenhouse', 'greenworkssunriseglobalmarketing'),
  ('GRVTY', 'greenhouse', 'grvty'),
  ('GSD&M', 'greenhouse', 'gsdm'),
  ('Guidepoint', 'greenhouse', 'guidepoint'),
  ('Gusto', 'greenhouse', 'gusto'),
  ('Haize Labs', 'greenhouse', 'haizelabs'),
  ('Harbinger Motors', 'greenhouse', 'harbingermotors'),
  ('Haven Studios', 'greenhouse', 'haven'),
  ('Health-E Commerce', 'greenhouse', 'fsastorecom'),
  ('HeartFlow', 'greenhouse', 'heartflowinc'),
  ('HELLBENDER', 'greenhouse', 'hellbenderinc'),
  ('HeyGen', 'greenhouse', 'heygen'),
  ('Hive Financial Systems', 'greenhouse', 'hivefinancialsystems'),
  ('Hone Health', 'greenhouse', 'honehealth'),
  ('Horace Mann', 'greenhouse', 'horacemannservicecorporation'),
  ('Horizon Industries', 'greenhouse', 'horizonindustrieslimited'),
  ('HPR (Hyannis Port Research)', 'greenhouse', 'hyannisportresearch'),
  ('HubSpot', 'greenhouse', 'hubspot'),
  ('Hudl', 'greenhouse', 'hudl'),
  ('HumanSignal', 'greenhouse', 'humansignal'),
  ('ID.me', 'greenhouse', 'idmeuniversityrecruiting'),
  ('IEM', 'greenhouse', 'industrialelectricmanufacturing'),
  ('IMC Trading', 'greenhouse', 'imc'),
  ('impact.com', 'greenhouse', 'impact'),
  ('Impinj', 'greenhouse', 'impinjexternal'),
  ('Impiricus', 'greenhouse', 'impiricus'),
  ('Incident IQ', 'greenhouse', 'incidentiq'),
  ('Inizio', 'greenhouse', 'inizio'),
  ('Innodata', 'greenhouse', 'innodatainc'),
  ('Inspire Medical Systems', 'greenhouse', 'inspiremedicalsystemsinc'),
  ('Instacart', 'greenhouse', 'instacart'),
  ('InstaLILY', 'greenhouse', 'instalilyai'),
  ('Instawork', 'greenhouse', 'instawork'),
  ('Instead', 'greenhouse', 'instead'),
  ('Integra FEC', 'greenhouse', 'integra'),
  ('Integra FEC', 'greenhouse', 'integrainterns'),
  ('Intrinsic', 'greenhouse', 'intrinsicrobotics'),
  ('Invisible Technologies AI', 'greenhouse', 'agency'),
  ('Iovance Biotherapeutics', 'greenhouse', 'iovancebiotherapeutics'),
  ('iSpot.tv', 'greenhouse', 'ispottv'),
  ('Ivalua', 'greenhouse', 'ivalua'),
  ('IVX Health', 'greenhouse', 'ivxhealth'),
  ('Jane Street', 'greenhouse', 'janestreet'),
  ('Jencap', 'greenhouse', 'jencapinc'),
  ('Jumio', 'greenhouse', 'jumio'),
  ('Juvare', 'greenhouse', 'juvare'),
  ('Kairos Power', 'greenhouse', 'kairospower'),
  ('Kapitus', 'greenhouse', 'kapitus'),
  ('Kargo', 'greenhouse', 'kargo'),
  ('Kensington', 'greenhouse', 'kensingtontours'),
  ('Kikoff', 'greenhouse', 'kikoff'),
  ('Klaviyo', 'greenhouse', 'klaviyocampus'),
  ('KnowBe4', 'greenhouse', 'knowbe4'),
  ('Koddi', 'greenhouse', 'koddi'),
  ('Kodiak Robotics', 'greenhouse', 'kodiak'),
  ('KRAFTON', 'greenhouse', 'studiokraftonboard'),
  ('Kroll Bond Rating Agency', 'greenhouse', 'krollbondratingagency'),
  ('Labelbox', 'greenhouse', 'labelbox'),
  ('Lasko Products', 'greenhouse', 'laskoproducts'),
  ('Later', 'greenhouse', 'later'),
  ('LaunchDarkly', 'greenhouse', 'launchdarkly'),
  ('Layer Health', 'greenhouse', 'layerhealth'),
  ('League', 'greenhouse', 'leagueinc'),
  ('Legend Biotech', 'greenhouse', 'legendcareers'),
  ('LG Electronics', 'greenhouse', 'lgelectronics'),
  ('LHV Bank', 'greenhouse', 'lhvuk'),
  ('Lightmatter', 'greenhouse', 'lightmatter'),
  ('Lightspeed Systems', 'greenhouse', 'lightspeedsystems'),
  ('Lila Sciences', 'greenhouse', 'lilasciences'),
  ('Locus Robotics', 'greenhouse', 'locusrobotics'),
  ('LogicGate', 'greenhouse', 'logicgate'),
  ('Lucid Bots', 'greenhouse', 'lucidbots'),
  ('Lucid Motors', 'greenhouse', 'lucidmotors'),
  ('Lumos', 'greenhouse', 'lumosfiber'),
  ('Lunar Energy', 'greenhouse', 'lunarenergy'),
  ('Lyft', 'greenhouse', 'lyft'),
  ('Madison Energy Infrastructure', 'greenhouse', 'madisonenergyinfrastructure'),
  ('Major League Baseball', 'greenhouse', 'philliesbaseballoperations'),
  ('Marqeta', 'greenhouse', 'mqreferrals'),
  ('Marshall Wace', 'greenhouse', 'mwinternshipprogram'),
  ('Maven Securities', 'greenhouse', 'emergingtalent'),
  ('Maven Securities', 'greenhouse', 'mavensecuritiesholdingltd'),
  ('Maybell Quantum Industries', 'greenhouse', 'maybellquantum'),
  ('McKinney', 'greenhouse', 'jobsmckinneycom'),
  ('McMaster-Carr', 'greenhouse', 'mcmastercarr'),
  ('MedElite', 'greenhouse', 'medelitellc'),
  ('Medical Informatics Engineering', 'greenhouse', 'medicalinformaticsengineering'),
  ('MEMIC', 'greenhouse', 'memic'),
  ('Mercury', 'greenhouse', 'mercury'),
  ('MERGE', 'greenhouse', 'mergeworld'),
  ('Meridian Partners', 'greenhouse', 'morsecorpcoop'),
  ('Meriton', 'greenhouse', 'meriton'),
  ('MerQube', 'greenhouse', 'merqube'),
  ('MetOx International', 'greenhouse', 'metoxinternationalinc'),
  ('Minitab', 'greenhouse', 'minitab'),
  ('Mobilityware', 'greenhouse', 'mobilityware'),
  ('Moment Energy', 'greenhouse', 'momentenergy'),
  ('MongoDB', 'greenhouse', 'mongodb'),
  ('mthree', 'greenhouse', 'mthreerecruitingportal'),
  ('Muon Space', 'greenhouse', 'muonspace'),
  ('National Information Solutions Cooperative (NISC)', 'greenhouse', 'nisc'),
  ('National Information Solutions Cooperative (NISC)', 'greenhouse', 'testnisc'),
  ('Neo4j', 'greenhouse', 'neo4j'),
  ('Neuralink', 'greenhouse', 'neuralink'),
  ('NewsBreak', 'greenhouse', 'newsbreak'),
  ('Newsela', 'greenhouse', 'newsela'),
  ('Newton Research', 'greenhouse', 'newtonresearch'),
  ('Nex', 'greenhouse', 'nex'),
  ('NICE', 'greenhouse', 'nice'),
  ('Nimble Gravity', 'greenhouse', 'nimblegravity'),
  ('Nooks', 'greenhouse', 'nooks'),
  ('Northspyre', 'greenhouse', 'northspyre'),
  ('Notability', 'greenhouse', 'gingerlabsinc'),
  ('NPR', 'greenhouse', 'nationalpublicradioinc'),
  ('OBE', 'greenhouse', 'oldcastlebuildingenvelope'),
  ('Obsidian Security', 'greenhouse', 'obsidiansecurity'),
  ('OceanX', 'greenhouse', 'oceanx'),
  ('Octaura', 'greenhouse', 'octaura'),
  ('OfferUp', 'greenhouse', 'offerup'),
  ('OH.io', 'greenhouse', 'ohio'),
  ('Okta', 'greenhouse', 'okta'),
  ('Olsson', 'greenhouse', 'olsson'),
  ('Omnicom Health', 'greenhouse', 'omnicomhealth'),
  ('Onapsis', 'greenhouse', 'onapsis'),
  ('Open Farm Pet', 'greenhouse', 'openfarminc'),
  ('OpenTable', 'greenhouse', 'opentable'),
  ('Optiver', 'greenhouse', 'optiverprivate'),
  ('Optiver', 'greenhouse', 'tradingacademy2025'),
  ('Orennia', 'greenhouse', 'orennia'),
  ('OTR Solutions', 'greenhouse', 'otrcapital1'),
  ('Oura', 'greenhouse', 'oura'),
  ('Pacvue', 'greenhouse', 'pacvue'),
  ('Pagaya Investments', 'greenhouse', 'pagaya'),
  ('Palmetto Clean Technology', 'greenhouse', 'palmettocleantech'),
  ('Parachute Health', 'greenhouse', 'parachutehealth'),
  ('Parallel Systems', 'greenhouse', 'parallel'),
  ('PatientPoint', 'greenhouse', 'patientpoint'),
  ('PDT Partners', 'greenhouse', 'pdtpartners'),
  ('Pendar Technologies', 'greenhouse', 'pendartechnologies'),
  ('Per Scholas', 'greenhouse', 'perscholashires'),
  ('Perpay', 'greenhouse', 'perpay'),
  ('Phaidra', 'greenhouse', 'phaidra'),
  ('Phamily', 'greenhouse', 'jobsatphamily'),
  ('Phoenix Contact', 'greenhouse', 'phoenixcontact'),
  ('PhysicsX', 'greenhouse', 'physicsx'),
  ('Piaggio Fast Forward', 'greenhouse', 'piaggiofastforward'),
  ('Pinterest', 'greenhouse', 'pinterest'),
  ('Planet', 'greenhouse', 'planetlabs'),
  ('PlanetScale', 'greenhouse', 'planetscale'),
  ('PlayStation', 'greenhouse', 'waterloocoop'),
  ('PLS', 'greenhouse', 'plscareers'),
  ('PMG', 'greenhouse', 'pmg'),
  ('Podium', 'greenhouse', 'podium81'),
  ('Point C', 'greenhouse', 'pointc'),
  ('Point72', 'greenhouse', 'point72'),
  ('PolyAI', 'greenhouse', 'polyai'),
  ('Postman', 'greenhouse', 'postman'),
  ('Practising Law Institute', 'greenhouse', 'practisinglawinstitute'),
  ('Praxent', 'greenhouse', 'praxent'),
  ('Premier Automation', 'greenhouse', 'premierautomation'),
  ('Presence', 'greenhouse', 'presencelearning'),
  ('Profluent', 'greenhouse', 'profluent'),
  ('Prolaio', 'greenhouse', 'prolaio'),
  ('Prophet', 'greenhouse', 'prophet'),
  ('Pure Storage', 'greenhouse', 'purestorage'),
  ('QGenda', 'greenhouse', 'qgenda'),
  ('QuEra Computing', 'greenhouse', 'queracomputinginc'),
  ('RA Capital Management', 'greenhouse', 'racapitalmanagementllc'),
  ('Rackner', 'greenhouse', 'rackner'),
  ('Radix Trading', 'greenhouse', 'radixuniversity'),
  ('Readystate Asset Management', 'greenhouse', 'readystate'),
  ('Realtor.com', 'greenhouse', 'rdccareers'),
  ('Reddit', 'greenhouse', 'reddit'),
  ('Redwood Materials', 'greenhouse', 'redwoodmaterials'),
  ('Relay', 'greenhouse', 'relaypro'),
  ('Rexford Industrial', 'greenhouse', 'rexfordindustrial'),
  ('RF-SMART', 'greenhouse', 'rfsmart'),
  ('Rhombus Power', 'greenhouse', 'rhombuspower'),
  ('Rise8', 'greenhouse', 'rise8'),
  ('Robinhood', 'greenhouse', 'robinhood'),
  ('RoboForce', 'greenhouse', 'roboforce'),
  ('Rocket Lab USA', 'greenhouse', 'rocketlab'),
  ('Rocket Lawyer', 'greenhouse', 'rocketlawyer'),
  ('RTW Investments', 'greenhouse', 'rtwinvestments'),
  ('Rugged Robotics', 'greenhouse', 'ruggedrobotics'),
  ('Sage', 'greenhouse', 'sage49'),
  ('Salient Motion', 'greenhouse', 'salientmotion'),
  ('SALT XC', 'greenhouse', 'saltxc'),
  ('Samaya', 'greenhouse', 'samayaai'),
  ('Samsung', 'greenhouse', 'samsungsemiconductor'),
  ('Samsung Research America', 'greenhouse', 'samsungresearchamericainternship'),
  ('SanMar', 'greenhouse', 'sanmar'),
  ('Scale AI', 'greenhouse', 'scaleai'),
  ('Schonfeld', 'greenhouse', 'schonfeld'),
  ('SchoolMint', 'greenhouse', 'schoolmint'),
  ('Scopely', 'greenhouse', 'scopely'),
  ('Scout Motors', 'greenhouse', 'scoutmotors'),
  ('Seurat Technologies', 'greenhouse', 'seurat'),
  ('Seven Research', 'greenhouse', 'sevenresearch'),
  ('Sezzle', 'greenhouse', 'sezzle'),
  ('SharkNinja', 'greenhouse', 'sharkninjaoperatingllc'),
  ('SHEIN', 'greenhouse', 'shein'),
  ('Sigma Computing', 'greenhouse', 'sigmacomputing'),
  ('Signifyd', 'greenhouse', 'signifyd95'),
  ('Sila Nanotechnologies', 'greenhouse', 'silananotechnologies'),
  ('Simple Technology Solutions', 'greenhouse', 'simpletechnologysolutions'),
  ('SK hynix', 'greenhouse', 'skhynixamerica'),
  ('Skyryse', 'greenhouse', 'skyryse'),
  ('Smartly.io', 'greenhouse', 'smartlyio'),
  ('Snorkel AI', 'greenhouse', 'snorkelai'),
  ('Solid Power', 'greenhouse', 'solidpower'),
  ('Sonatus', 'greenhouse', 'sonatus'),
  ('Sono Bello', 'greenhouse', 'sonobello'),
  ('SonoThera', 'greenhouse', 'sonothera'),
  ('Sony Interactive Entertainment', 'greenhouse', 'sonyinteractiveentertainmentglobal'),
  ('Space Kinetic', 'greenhouse', 'spacekinetic'),
  ('SpaceX', 'greenhouse', 'spacex'),
  ('Sparksoft', 'greenhouse', 'sparksoftcorporation'),
  ('SpecterOps', 'greenhouse', 'specterops'),
  ('Speechmatics', 'greenhouse', 'speechmatics'),
  ('SpyCloud', 'greenhouse', 'spycloud'),
  ('Starburst', 'greenhouse', 'starburst'),
  ('StockX', 'greenhouse', 'stockx'),
  ('STR', 'greenhouse', 'systemstechnologyresearch'),
  ('Strand Therapeutics', 'greenhouse', 'strandtherapeutics'),
  ('Strata Decision Technology', 'greenhouse', 'stratacareers'),
  ('Stripe', 'greenhouse', 'stripe'),
  ('SuccessKPI', 'greenhouse', 'successkpiinc'),
  ('SupplyHouse.com', 'greenhouse', 'supplyhouse'),
  ('Syska Hennessy Group', 'greenhouse', 'syskahennessy'),
  ('Tastylive', 'greenhouse', 'tastylive'),
  ('tastytrade', 'greenhouse', 'tastytrade'),
  ('Tatari', 'greenhouse', 'tatari'),
  ('Technergetics', 'greenhouse', 'technergetics'),
  ('Tecovas', 'greenhouse', 'tecovas'),
  ('Tenon', 'greenhouse', 'tenon'),
  ('Tenstorrent', 'greenhouse', 'tenstorrentuniversity'),
  ('Terran Orbital', 'greenhouse', 'terranorbitalcorporation'),
  ('The Allen Institute for AI', 'greenhouse', 'thealleninstitute'),
  ('The Health Management Academy', 'greenhouse', 'thehealthmanagementacademy'),
  ('The New York Times', 'greenhouse', 'thenewyorktimes'),
  ('The Nuclear Company', 'greenhouse', 'thenuclearcompany'),
  ('The Trade Desk', 'greenhouse', 'thetradedesk'),
  ('The Weather Company', 'greenhouse', 'theweathercompany'),
  ('Together AI', 'greenhouse', 'togetherai'),
  ('Torc Robotics', 'greenhouse', 'torcrobotics'),
  ('Toshiba Global Commerce', 'greenhouse', 'toshibaglobalcommercesolutions'),
  ('TransMarket Group', 'greenhouse', 'transmarketgroup'),
  ('Trexon', 'greenhouse', 'tpcengineeringholdingsllc'),
  ('TribalScale', 'greenhouse', 'tribalscale'),
  ('TripArc', 'greenhouse', 'triparc'),
  ('True Anomaly', 'greenhouse', 'trueanomalyinc'),
  ('Trumid', 'greenhouse', 'trumid'),
  ('Truveta', 'greenhouse', 'truveta'),
  ('Tubi', 'greenhouse', 'tubitv'),
  ('Twilio', 'greenhouse', 'twilio'),
  ('Two Six Technologies', 'greenhouse', 'twosixtechnologies'),
  ('Typeface', 'greenhouse', 'typeface'),
  ('Uber Freight', 'greenhouse', 'uberfreight'),
  ('Udemy', 'greenhouse', 'udemybedi'),
  ('Ultima Genomics', 'greenhouse', 'ultimagenomics'),
  ('UnitedMasters', 'greenhouse', 'unitedmasterstranslation'),
  ('University of Virginia Investment Management Company (UVIMCO)', 'greenhouse', 'uvimco'),
  ('Upstream USA', 'greenhouse', 'upstreamusa'),
  ('USAFacts', 'greenhouse', 'usafacts'),
  ('Varda Space', 'greenhouse', 'vardaspace'),
  ('Veeam Software', 'greenhouse', 'veeamsoftware'),
  ('Vera Institute of Justice', 'greenhouse', 'verainstituteofjustice'),
  ('Vercel', 'greenhouse', 'vercel'),
  ('Verisign', 'greenhouse', 'verisign'),
  ('Verkada', 'greenhouse', 'verkada'),
  ('Vestwell', 'greenhouse', 'vestwell'),
  ('Viking Global', 'greenhouse', 'vikingglobalinvestors'),
  ('Virtru', 'greenhouse', 'virtru'),
  ('Virtu Financial', 'greenhouse', 'virtu'),
  ('Vise', 'greenhouse', 'viseai'),
  ('Visier Solutions', 'greenhouse', 'visiersolutionsinc'),
  ('Vixxo', 'greenhouse', 'vixxo'),
  ('Voloridge', 'greenhouse', 'voloridgeinvestmentmanagement'),
  ('Voyager Technologies', 'greenhouse', 'voyagertechnologiesinc'),
  ('VSC Fire & Security', 'greenhouse', 'vscfiresecurityinc'),
  ('Vulcan Elements', 'greenhouse', 'vulcanelements'),
  ('Walleye Capital', 'greenhouse', 'walleyecapital-external-students'),
  ('Wasabi Technologies', 'greenhouse', 'wasabi'),
  ('Weiss Asset Management', 'greenhouse', 'weissassetmanagement'),
  ('Wheely', 'greenhouse', 'wheely'),
  ('WhiteWater Midstream', 'greenhouse', 'whitewatermidstream'),
  ('Workato', 'greenhouse', 'workato'),
  ('Workstream', 'greenhouse', 'workstream'),
  ('World Surf League', 'greenhouse', 'worldsurfleague'),
  ('WPP Media', 'greenhouse', 'wppmedia'),
  ('Wurl', 'greenhouse', 'wurljobs'),
  ('Xaira Therapeutics', 'greenhouse', 'xairatherapeutics'),
  ('Xantium', 'greenhouse', 'xantium'),
  ('Xebia', 'greenhouse', 'xebiausa'),
  ('XPENG Motors', 'greenhouse', 'xpengmotors'),
  ('XTX Markets', 'greenhouse', 'xtxmarketstechnologies'),
  ('Yes Energy', 'greenhouse', 'yesenergy'),
  ('YOU.com', 'greenhouse', 'youcom'),
  ('Zipline', 'greenhouse', 'flyzipline'),
  ('Zocdoc', 'greenhouse', 'zocdoc'),
  ('Zone 5 Technologies', 'greenhouse', 'zone5technologies'),
  ('Zscaler', 'greenhouse', 'zscaler'),
  ('Acceldata', 'lever', 'acceldata'),
  ('Achievers', 'lever', 'achievers'),
  ('Actian', 'lever', 'actian'),
  ('Age of Learning', 'lever', 'aofl'),
  ('AHEAD', 'lever', 'thinkahead'),
  ('Aledade', 'lever', 'aledade'),
  ('Alertus Technologies', 'lever', 'alertus'),
  ('Allegiant Air', 'lever', 'allegiantair'),
  ('AllTrails', 'lever', 'alltrails'),
  ('AltaML', 'lever', 'altaml'),
  ('Analytic Partners', 'lever', 'analyticpartners'),
  ('Anomali', 'lever', 'anomali'),
  ('Appen', 'lever', 'appen-2'),
  ('Aquabyte', 'lever', 'aquabyte'),
  ('Arc''teryx Equipment', 'lever', 'arcteryx.com'),
  ('ArteraAI', 'lever', 'artera'),
  ('Behaviour Interactive', 'lever', 'bhvr'),
  ('Belvedere Trading', 'lever', 'belvederetrading'),
  ('BenchSci', 'lever', 'benchsci'),
  ('Beta Technologies', 'lever', 'beta'),
  ('BioAgilytix', 'lever', 'bioagilytix'),
  ('BlueRock Therapeutics', 'lever', 'bluerocktx'),
  ('Bright Machines', 'lever', 'brightmachines'),
  ('Brooks Running', 'lever', 'brooksrunning'),
  ('ButcherBox', 'lever', 'butcherbox'),
  ('CALSTART', 'lever', 'calstart'),
  ('Catalist', 'lever', 'catalist'),
  ('Center for AI Safety', 'lever', 'aisafety'),
  ('Cirque du Soleil', 'lever', 'cirquedusoleil'),
  ('CLO Virtual Fashion', 'lever', 'clovirtualfashion'),
  ('Cloudforce', 'lever', 'go-cloudforce'),
  ('Coupa Software', 'lever', 'coupa'),
  ('Crest Industries', 'lever', 'crestoperations'),
  ('Daniels Health', 'lever', 'daniels-sharpsmart'),
  ('Democratic Governors Association', 'lever', 'dga'),
  ('Diversified Automation', 'lever', 'diversified-automation'),
  ('Drivemode', 'lever', 'drivemode'),
  ('E-Space', 'lever', 'espace'),
  ('Ekimetrics', 'lever', 'ekimetrics'),
  ('Eko Health', 'lever', 'ekohealth'),
  ('Elf Beauty', 'lever', 'elfbeauty'),
  ('Elk Valley Resources', 'lever', 'evr'),
  ('Endpoint Clinical', 'lever', 'endpointclinical'),
  ('EQ Bank', 'lever', 'eqbank'),
  ('Equativ', 'lever', 'equativ'),
  ('EV Realty', 'lever', 'evrealty-us'),
  ('Exowatt', 'lever', 'exowatt'),
  ('Extreme Networks', 'lever', 'extremenetworks'),
  ('Farfetch', 'lever', 'farfetch'),
  ('Fehr & Peers', 'lever', 'fehrandpeers'),
  ('Field AI', 'lever', 'field-ai'),
  ('Firemon', 'lever', 'firemon'),
  ('Fluxergy', 'lever', 'fluxergy-2'),
  ('Fullscript', 'lever', 'fullscript'),
  ('GenBio AI', 'lever', 'genbio'),
  ('GeoComply', 'lever', 'geocomply-2'),
  ('GoMaterials', 'lever', 'gomaterials'),
  ('Gr0', 'lever', 'gr0'),
  ('Great Gray', 'lever', 'great-gray-group'),
  ('Greenlight', 'lever', 'greenlight'),
  ('Hanna Andersson', 'lever', 'hannaandersson'),
  ('Hermeus', 'lever', 'hermeus'),
  ('HRL Laboratories', 'lever', 'dodmg'),
  ('Ibility', 'lever', 'ibility'),
  ('Ideas United', 'lever', 'ideasunited'),
  ('IMO Health', 'lever', 'imo-online'),
  ('Institute of Foundation Models', 'lever', 'ifm-us'),
  ('Intropic', 'lever', 'intropic'),
  ('Ivo', 'lever', 'ivo'),
  ('Kabam', 'lever', 'kabam'),
  ('Kepler Communications', 'lever', 'kepler'),
  ('Kpler', 'lever', 'kpler'),
  ('Larian Studios', 'lever', 'larian'),
  ('Lendbuzz', 'lever', 'lendbuzz'),
  ('Level AI', 'lever', 'levelai'),
  ('Lexeo Therapeutics', 'lever', 'lexeotx'),
  ('Lightcast', 'lever', 'economicmodeling'),
  ('Long Wall', 'lever', 'longwall'),
  ('LTA Research', 'lever', 'ltaresearch'),
  ('Magnet Forensics', 'lever', 'magnetforensics'),
  ('Multiply Labs', 'lever', 'multiplylabs'),
  ('Neighbor', 'lever', 'neighbor'),
  ('Nextech Systems', 'lever', 'nextech'),
  ('NextGen Federal Systems', 'lever', 'nextgenfed'),
  ('Nobull', 'lever', 'nobullproject'),
  ('Octopus Energy', 'lever', 'octoenergy'),
  ('Oleria Security', 'lever', 'oleria-security'),
  ('OpenX', 'lever', 'openx'),
  ('OraSure Technologies', 'lever', 'dnagenotek'),
  ('Palantir', 'lever', 'palantir'),
  ('Parallel Wireless', 'lever', 'parallelwireless'),
  ('Pelmorex', 'lever', 'pelmorex'),
  ('Penta Group', 'lever', 'pentagrp'),
  ('Penumbra Inc', 'lever', 'penumbrainc'),
  ('PingWind', 'lever', 'pingwind'),
  ('Pivot Energy', 'lever', 'pivotenergy'),
  ('Pivotal Software', 'lever', 'pivotal'),
  ('PlusAI', 'lever', 'plus-2'),
  ('Prosper Funding', 'lever', 'prosper'),
  ('Quandri', 'lever', 'quandri'),
  ('QuantCo', 'lever', 'quantco-'),
  ('Rainmaker', 'lever', 'make-rain'),
  ('RAVL', 'lever', 'ravl_io'),
  ('Redhorse', 'lever', 'redhorsecorp'),
  ('Redwood Credit Union', 'lever', 'redwoodcu'),
  ('Reli', 'lever', 'shopreli'),
  ('Reply', 'lever', 'reply'),
  ('Rigetti', 'lever', 'rigetti'),
  ('Robust.ai', 'lever', 'robust-ai'),
  ('RWS', 'lever', 'rws'),
  ('Samba TV', 'lever', 'sambatv'),
  ('Saronic', 'lever', 'saronic'),
  ('Secureframe', 'lever', 'secureframe'),
  ('SF Giants', 'lever', 'sfgiants'),
  ('SFMOMA', 'lever', 'sfmoma'),
  ('Shield AI', 'lever', 'shieldai'),
  ('ShyftLabs', 'lever', 'shyftlabs'),
  ('Skyways', 'lever', 'skyways'),
  ('SoloPulse', 'lever', 'solopulseco'),
  ('Spotify', 'lever', 'spotify'),
  ('Stand Together', 'lever', 'standtogether'),
  ('SteerBridge', 'lever', 'steerbridge'),
  ('SunSource', 'lever', 'sunsrce'),
  ('Sunwater Capital', 'lever', 'sunwatercapital'),
  ('Syntax', 'lever', 'syntax'),
  ('Synthego', 'lever', 'synthego'),
  ('Tahoe Therapeutics', 'lever', 'tahoebio-ai'),
  ('Tekton', 'lever', 'tekton'),
  ('Teleo', 'lever', 'teleo'),
  ('Telesat', 'lever', 'telesat'),
  ('Telligen', 'lever', 'telligen'),
  ('The Information Lab', 'lever', 'theinformationlab'),
  ('Toyota Research Institute', 'lever', 'tri'),
  ('Traackr', 'lever', 'traackr'),
  ('UntilLabs', 'lever', 'until'),
  ('Veeva Systems', 'lever', 'veeva'),
  ('Very Good Security', 'lever', 'verygoodsecurity'),
  ('Vevo', 'lever', 'vevo'),
  ('Vivenu', 'lever', 'vivenu'),
  ('Voltus', 'lever', 'voltus'),
  ('Waabi', 'lever', 'waabi'),
  ('Wade Trim', 'lever', 'wadetrim'),
  ('Wealthsimple', 'lever', 'wealthsimple'),
  ('WeRide', 'lever', 'weride'),
  ('Woven', 'lever', 'woven-by-toyota'),
  ('Xsolla', 'lever', 'xsolla'),
  ('zaimler', 'lever', 'zaimler'),
  ('Zoox', 'lever', 'zoox'),
  ('Zus Health', 'lever', 'zushealth'),
  ('1Password', 'ashby', '1password'),
  ('1X', 'ashby', '1x'),
  ('8VC', 'ashby', '8vc'),
  ('Abridge', 'ashby', 'abridge'),
  ('Abundant', 'ashby', 'abundant'),
  ('Adaption Labs', 'ashby', 'adaption'),
  ('Adaptive Security', 'ashby', 'adaptivesecurity'),
  ('AeroVect', 'ashby', 'aerovect'),
  ('AfterQuery', 'ashby', 'afterquery'),
  ('Agentis Capital', 'ashby', 'agentis-capital-advisors'),
  ('AI Intern to the CEO', 'ashby', 'cyvl'),
  ('Airspace Intelligence', 'ashby', 'airspace-intelligence.com'),
  ('Alljoined', 'ashby', 'alljoined'),
  ('Alloy Enterprises', 'ashby', 'alloyenterprises'),
  ('ALSO', 'ashby', 'ridealso'),
  ('Ambrook', 'ashby', 'ambrook'),
  ('Anterior', 'ashby', 'anterior'),
  ('Anthelion Capital', 'ashby', 'anthelioncap'),
  ('Apex', 'ashby', 'apex-technology-inc'),
  ('Applied Intuition', 'ashby', 'applied'),
  ('Aptura', 'ashby', 'aptura'),
  ('Architect Labs', 'ashby', 'architect'),
  ('Astera', 'ashby', 'astera'),
  ('Astronomer', 'ashby', 'astronomer'),
  ('Auctor', 'ashby', 'auctor'),
  ('Base Power', 'ashby', 'base-power'),
  ('Baseten', 'ashby', 'baseten'),
  ('Basis Research Institute', 'ashby', 'basis-research'),
  ('Beacon Software', 'ashby', 'beaconsoftware'),
  ('Benchling', 'ashby', 'benchling'),
  ('Bild AI', 'ashby', 'bild-ai'),
  ('Binance', 'ashby', 'binance.us'),
  ('Blackbird Labs', 'ashby', 'blackbird-labs-inc'),
  ('Blockhouse', 'ashby', 'blockhouse'),
  ('Bloxd', 'ashby', 'bloxd'),
  ('Brain Co.', 'ashby', 'brainco'),
  ('Bree', 'ashby', 'bree'),
  ('Cartesia', 'ashby', 'cartesia'),
  ('Centerfield', 'ashby', 'centerfield'),
  ('Charge Robotics', 'ashby', 'charge-robotics'),
  ('Circleback', 'ashby', 'circleback'),
  ('Clera', 'ashby', 'clera'),
  ('Clipboard Health', 'ashby', 'clipboard'),
  ('Cohere', 'ashby', 'cohere'),
  ('Collaborative Robotics', 'ashby', 'cobot'),
  ('Colonist', 'ashby', 'colonist'),
  ('Compa', 'ashby', 'compa'),
  ('Composio', 'ashby', 'composio'),
  ('Confluent', 'ashby', 'confluent'),
  ('Constellation Space', 'ashby', 'constellationspace'),
  ('Context', 'ashby', 'context'),
  ('Coverdash', 'ashby', 'coverdash'),
  ('Creatify', 'ashby', 'embedding-vc'),
  ('Creatify Lab', 'ashby', 'creatify'),
  ('Crosby', 'ashby', 'crosby'),
  ('Crusoe', 'ashby', 'crusoe'),
  ('CTGT', 'ashby', 'ctgt'),
  ('CuspAI', 'ashby', 'cuspai'),
  ('Cybernetic Labs', 'ashby', 'netic'),
  ('d-Matrix', 'ashby', 'd-matrix'),
  ('Dedalus Labs', 'ashby', 'dedalus-labs'),
  ('Deepgram', 'ashby', 'deepgram'),
  ('Delinea', 'ashby', 'delinea'),
  ('Deliveroo', 'ashby', 'deliveroo'),
  ('Dexmate', 'ashby', 'dexmate'),
  ('Ditto', 'ashby', 'ditto'),
  ('Ditto AI', 'ashby', 'dittoai'),
  ('Droyd Robotics', 'ashby', 'droyd'),
  ('Dryft', 'ashby', 'dryft'),
  ('Egra', 'ashby', 'egra'),
  ('Eigen Labs', 'ashby', 'eigen-labs'),
  ('Eight Sleep', 'ashby', 'eightsleep'),
  ('Ellipsis Labs', 'ashby', 'ellipsislabs'),
  ('Eloquent AI', 'ashby', 'eloquentai'),
  ('Epia Neuro', 'ashby', 'epianeuro'),
  ('Equip Health', 'ashby', 'equip'),
  ('Eragon', 'ashby', 'eragon'),
  ('Espa AI', 'ashby', 'espa'),
  ('Etched', 'ashby', 'etched'),
  ('ether.fi', 'ashby', 'ether.fi'),
  ('Exa Labs', 'ashby', 'exa'),
  ('Eyebot', 'ashby', 'eyebot'),
  ('Fab2', 'ashby', 'fab2'),
  ('Faculte', 'ashby', 'faculty-fellowship'),
  ('Faculty AI', 'ashby', 'faculty'),
  ('Farsight', 'ashby', 'farsight'),
  ('Firetiger', 'ashby', 'firetiger'),
  ('Flagright', 'ashby', 'flagright.com'),
  ('Fluency', 'ashby', 'fluency'),
  ('Forus', 'ashby', 'forus'),
  ('Frontier Health', 'ashby', 'frontier-health'),
  ('Fundwell', 'ashby', 'fundwell'),
  ('G2', 'ashby', 'g2'),
  ('Gamechanger', 'ashby', 'gamechanger'),
  ('Gecko Robotics', 'ashby', 'gecko-robotics'),
  ('Gen Digital', 'ashby', 'gen-digital'),
  ('General Intuition &amp; Medal', 'ashby', 'generalintuition-medal'),
  ('GenMD', 'ashby', 'genmd'),
  ('Georgian Partners Growth', 'ashby', 'georgian'),
  ('Giga AI', 'ashby', 'gigaml'),
  ('Glimpse Engineering', 'ashby', 'glimp-se'),
  ('GoLinks', 'ashby', 'golinks'),
  ('Gorgias', 'ashby', 'gorgias'),
  ('GrayMatter Robotics', 'ashby', 'graymatter-robotics'),
  ('Great Question', 'ashby', 'greatquestion'),
  ('Gritt Robotics Inc', 'ashby', 'gritt'),
  ('Gumloop', 'ashby', 'gumloop'),
  ('H3X Technologies', 'ashby', 'h3x-technologies'),
  ('Hadrian', 'ashby', 'hadrian-automation'),
  ('Handshake', 'ashby', 'handshake'),
  ('Harvey', 'ashby', 'harvey'),
  ('Hawk-Eye Innovations', 'ashby', 'hawkeyeinnovations'),
  ('Hayden AI', 'ashby', 'haydenai'),
  ('HCompany', 'ashby', 'hcompany'),
  ('Heliux', 'ashby', 'heliux'),
  ('Heron Data', 'ashby', 'herondata'),
  ('Heron Power', 'ashby', 'heron-power'),
  ('Higharc', 'ashby', 'higharc'),
  ('Hiverge', 'ashby', 'hiverge'),
  ('Homebase', 'ashby', 'homebase'),
  ('Hubs.is', 'ashby', 'hubs.is'),
  ('Human Computer Lab', 'ashby', 'human-computer-lab'),
  ('Hypercubic', 'ashby', 'hypercubic'),
  ('Illumio', 'ashby', 'illumio'),
  ('Inherent', 'ashby', 'inherent'),
  ('Insitro', 'ashby', 'insitro'),
  ('Internship', 'ashby', 'interplay'),
  ('Ironclad', 'ashby', 'ironcladhq'),
  ('Junior AI', 'ashby', 'junior'),
  ('Juniper Square', 'ashby', 'junipersquare'),
  ('k-ID', 'ashby', 'k-id'),
  ('Kastle AI', 'ashby', 'kastle'),
  ('Keyrock', 'ashby', 'keyrock'),
  ('Kinetic Systems', 'ashby', 'kineticsystems'),
  ('Kira', 'ashby', 'kira'),
  ('Kirin', 'ashby', 'kirin'),
  ('Kognitos', 'ashby', 'kognitos'),
  ('Kong', 'ashby', 'kong'),
  ('kos.ai', 'ashby', 'kos.ai'),
  ('Lambda', 'ashby', 'lambda'),
  ('Leland', 'ashby', 'leland'),
  ('Linear', 'ashby', 'linear'),
  ('LINQ', 'ashby', 'linqapp'),
  ('Lovable', 'ashby', 'lovable'),
  ('Lunon', 'ashby', 'lunon'),
  ('Lydian', 'ashby', 'lydian'),
  ('m13', 'ashby', 'm13'),
  ('Mach Industries', 'ashby', 'mach'),
  ('Mach9', 'ashby', 'mach9'),
  ('Mariana Minerals', 'ashby', 'marianaminerals'),
  ('Matterworks', 'ashby', 'matterworks'),
  ('Maxima', 'ashby', 'maxima'),
  ('Maximor AI', 'ashby', 'maximor'),
  ('Maxinsights', 'ashby', 'maxinsights'),
  ('Medra', 'ashby', 'medraai'),
  ('Melius', 'ashby', 'melius'),
  ('Melotech', 'ashby', 'melotech'),
  ('Mercor', 'ashby', 'mercor'),
  ('Meshy', 'ashby', 'meshy'),
  ('Mistral AI', 'ashby', 'mistral.ai'),
  ('Modal', 'ashby', 'modal'),
  ('Monarch Money', 'ashby', 'monarchmoney'),
  ('Monogram', 'ashby', 'monogram'),
  ('MUBI', 'ashby', 'mubi'),
  ('Nash', 'ashby', 'nash'),
  ('NationGraph', 'ashby', 'nationgraph'),
  ('Navi AI', 'ashby', 'navi'),
  ('NeoCognition', 'ashby', 'neocognition'),
  ('New Lantern', 'ashby', 'newlantern'),
  ('Niural', 'ashby', 'niural'),
  ('Normal Computing', 'ashby', 'normalcomputing'),
  ('NORY', 'ashby', 'nory-co'),
  ('Notion', 'ashby', 'notion'),
  ('NOX METALS', 'ashby', 'nox-metals'),
  ('NTT DATA AIVista', 'ashby', 'ntt-data-aivista'),
  ('Nuclear Promise X', 'ashby', 'npx'),
  ('Obvious', 'ashby', 'obvious'),
  ('Odin Dynamics, Inc', 'ashby', 'odin-dynamics'),
  ('Odyssey', 'ashby', 'odysseyml'),
  ('Oligo Space', 'ashby', 'oligo'),
  ('Ontic', 'ashby', 'ontic'),
  ('OpenAI', 'ashby', 'openai'),
  ('OpusClip', 'ashby', 'opusclip'),
  ('Orbital Industries', 'ashby', 'orbitalindustries'),
  ('Osmo', 'ashby', 'osmo'),
  ('Outmarket AI', 'ashby', 'outmarket'),
  ('Outpost Technologies', 'ashby', 'outpostnow'),
  ('Output Biosciences', 'ashby', 'output'),
  ('Overview Energy', 'ashby', 'overviewenergy'),
  ('Parallel Web Systems', 'ashby', 'parallel'),
  ('Parspec', 'ashby', 'parspec'),
  ('Patreon', 'ashby', 'patreon'),
  ('Pebl', 'ashby', 'pebl'),
  ('Perchwell', 'ashby', 'perchwell'),
  ('Periodic Labs', 'ashby', 'periodic-labs'),
  ('Perplexity AI', 'ashby', 'perplexity'),
  ('Persona', 'ashby', 'persona'),
  ('Persona AI', 'ashby', 'persona.ai'),
  ('Phia', 'ashby', 'phia'),
  ('Phil', 'ashby', 'phil'),
  ('Phlair', 'ashby', 'phlair'),
  ('Phoebe', 'ashby', 'phoebe-work'),
  ('Phonely', 'ashby', 'phonely'),
  ('Phonic', 'ashby', 'phonic'),
  ('Physical Intelligence', 'ashby', 'physicalintelligence'),
  ('Pika', 'ashby', 'pika'),
  ('Pivot Robotics', 'ashby', 'pivotrobotics'),
  ('Polymath', 'ashby', 'polymath'),
  ('Poshmark', 'ashby', 'poshmark'),
  ('Prime Intellect', 'ashby', 'primeintellect'),
  ('Prior Labs', 'ashby', 'prior-labs'),
  ('Proxima', 'ashby', 'proxima'),
  ('Pylon', 'ashby', 'pylon-labs'),
  ('Quadrillion', 'ashby', 'quadrillion-labs'),
  ('Ramp', 'ashby', 'ramp'),
  ('RapDev', 'ashby', 'rapdev'),
  ('Reality Defender', 'ashby', 'realitydefender'),
  ('Realm', 'ashby', 'realmalliance'),
  ('Reflect Orbital', 'ashby', 'reflect-orbital'),
  ('Relay Financial', 'ashby', 'relayfi'),
  ('Remarcable', 'ashby', 'remarcable-inc'),
  ('Replit', 'ashby', 'replit'),
  ('Revise Robotics', 'ashby', 'reviserobotics'),
  ('Rho', 'ashby', 'rho'),
  ('Riveron', 'ashby', 'riveron'),
  ('Rivet Industries', 'ashby', 'rivet'),
  ('Rivian and Volkswagen Group Technologies', 'ashby', 'rivianvw.tech'),
  ('Roam', 'ashby', 'tryroam'),
  ('Rocket Science Group', 'ashby', 'rocketsciencegg'),
  ('Root Access', 'ashby', 'root-access'),
  ('Rundoo', 'ashby', 'rundoo'),
  ('SandboxAQ', 'ashby', 'sandboxaq'),
  ('Saronic', 'ashby', 'saronic'),
  ('Sentra', 'ashby', 'sentra'),
  ('Sentry', 'ashby', 'sentry'),
  ('Sereact', 'ashby', 'sereact'),
  ('Serval', 'ashby', 'serval'),
  ('Sierra', 'ashby', 'sierra'),
  ('Sieve', 'ashby', 'sieve'),
  ('Skydio', 'ashby', 'skydio'),
  ('Snowflake', 'ashby', 'snowflake'),
  ('Socket', 'ashby', 'socket'),
  ('Socure', 'ashby', 'socure'),
  ('Solink', 'ashby', 'solink'),
  ('Spacial AI', 'ashby', 'spacial'),
  ('Span', 'ashby', 'span'),
  ('Stand Insurance', 'ashby', 'standinsurance'),
  ('Super', 'ashby', 'super.com'),
  ('Sweatpals', 'ashby', 'sweatpals'),
  ('Taara', 'ashby', 'taaraconnect'),
  ('Tacit', 'ashby', 'tacit'),
  ('Tempo', 'ashby', 'tempo-io'),
  ('TensorWave', 'ashby', 'tensorwave'),
  ('Terminal', 'ashby', 'terminal'),
  ('Terranova', 'ashby', 'terranova'),
  ('Tessera Labs', 'ashby', 'tessera-labs'),
  ('The Voleon Group', 'ashby', 'voleon'),
  ('Tilde Research', 'ashby', 'tilderesearch'),
  ('tldraw', 'ashby', 'tldraw'),
  ('Tonal', 'ashby', 'tonal'),
  ('Treefera', 'ashby', 'treefera'),
  ('Triumph', 'ashby', 'triumph-arcade'),
  ('Turion Space', 'ashby', 'turion-space'),
  ('UiPath', 'ashby', 'uipath'),
  ('Uncountable', 'ashby', 'uncountable'),
  ('Unify', 'ashby', 'unify'),
  ('Unlikely AI', 'ashby', 'unlikelyai'),
  ('Unwrap', 'ashby', 'unwrap'),
  ('Upvest', 'ashby', 'upvest'),
  ('Valstad', 'ashby', 'valstad'),
  ('Vantage', 'ashby', 'vantage'),
  ('Varick Agents', 'ashby', 'varick-agents'),
  ('Veeda AI', 'ashby', 'veeda-labs'),
  ('Vega Investment Technologies', 'ashby', 'vega'),
  ('Vendelux', 'ashby', 'vendelux'),
  ('Vital Lyfe', 'ashby', 'vital-lyfe'),
  ('Vmax AI Corp', 'ashby', 'vmax'),
  ('Voldex', 'ashby', 'voldex'),
  ('Wealth.com', 'ashby', 'wealth-com'),
  ('Wealthsimple', 'ashby', 'wealthsimple'),
  ('Weave', 'ashby', 'weave'),
  ('WebAI', 'ashby', 'webai'),
  ('WindBorne Systems', 'ashby', 'windborne-systems'),
  ('Worldly', 'ashby', 'worldly'),
  ('Yotta Labs', 'ashby', 'yotta'),
  ('Zello', 'ashby', 'zello'),
  ('Zettabyte', 'ashby', 'zettabyte-space'),
  ('Zip', 'ashby', 'zip'),
  ('Zuru', 'ashby', 'zuru'),
  ('Alayacare', 'greenhouse', 'alayacare'),
  ('AlixPartners', 'greenhouse', 'alixpartners'),
  ('AMI', 'ashby', 'ami'),
  ('AnaVation', 'lever', 'anavationllc'),
  ('Artisan Partners', 'greenhouse', 'artisanpartners'),
  ('ASM International', 'greenhouse', 'asm'),
  ('Atomic Semi', 'ashby', 'atomicsemi'),
  ('Bland AI', 'ashby', 'bland'),
  ('CesiumAstro', 'lever', 'CesiumAstro'),
  ('Clerkie', 'greenhouse', 'clerkie'),
  ('Datadog', 'greenhouse', 'datadog'),
  ('Dmg Media', 'greenhouse', 'dmgmedia'),
  ('Epic Games', 'greenhouse', 'epicgames'),
  ('Everstream Analytics', 'greenhouse', 'everstreamanalytics'),
  ('Helsing', 'greenhouse', 'helsing'),
  ('Hippocratic AI', 'ashby', 'Hippocratic AI'),
  ('Jump Trading', 'greenhouse', 'jumptrading'),
  ('Nextiva', 'greenhouse', 'nextiva'),
  ('Nomagic', 'lever', 'Nomagic'),
  ('Old Mission', 'greenhouse', 'oldmissioncapital'),
  ('PsiQuantum', 'greenhouse', 'psiquantum'),
  ('Roblox', 'greenhouse', 'roblox'),
  ('Samsara', 'greenhouse', 'samsara'),
  ('Squarepoint Capital', 'greenhouse', 'squarepointcapital'),
  ('TELUS Digital', 'ashby', 'telus-digital'),
  ('The Browser Company', 'ashby', 'the browser company'),
  ('TIFIN', 'greenhouse', 'tifin'),
  ('Tower Research Capital', 'greenhouse', 'towerresearchcapital'),
  ('Trillium', 'greenhouse', 'trillium'),
  ('Verne Robotics', 'ashby', 'Verne Robotics'),
  ('Xpansiv', 'lever', 'Xpansiv '),
  ('AQR Capital Management', 'greenhouse', 'aqr'),
  ('Business Insider', 'greenhouse', 'insider'),
  ('Optiver', 'greenhouse', 'optiverus'),
  ('StepStone Group', 'greenhouse', 'stepstone'),
  ('Arlington County VA', 'oracle', 'fa-exkk-saasfaprod1.fa.ocs.oraclecloud.com|CX_1'),
  ('ATCO', 'oracle', 'eezy.fa.ca2.oraclecloud.com|CX'),
  ('Berkshire Hathaway Energy', 'oracle', 'fa-essf-saasfaprod1.fa.ocs.oraclecloud.com|CX_1'),
  ('Black Box', 'oracle', 'eoje.fa.us2.oraclecloud.com|CX_1001'),
  ('Blue Cross Blue Shield of Michigan', 'oracle', 'ejko.fa.us2.oraclecloud.com|CX_3'),
  ('CSX', 'oracle', 'fa-eowa-saasfaprod1.fa.ocs.oraclecloud.com|CSXCareers'),
  ('Duracell', 'oracle', 'fa-ewub-saasfaprod1.fa.ocs.oraclecloud.com|CX_26'),
  ('Fanatics', 'oracle', 'fa-exki-saasfaprod1.fa.ocs.oraclecloud.com|CX_1'),
  ('GCI', 'oracle', 'edqv.fa.us2.oraclecloud.com|CX'),
  ('Grant Thornton', 'oracle', 'ehzq.fa.us2.oraclecloud.com|CX_1'),
  ('GuideWell Mutual', 'oracle', 'fa-etum-saasfaprod1.fa.ocs.oraclecloud.com|CX_1'),
  ('Hoffman Construction', 'oracle', 'efsp.fa.us6.oraclecloud.com|CX'),
  ('Hunt Oil Company', 'oracle', 'fa-eqcd-saasfaprod1.fa.ocs.oraclecloud.com|CX_1'),
  ('Navy Federal', 'oracle', 'fa-etbx-saasfaprod1.fa.ocs.oraclecloud.com|nfcu'),
  ('Savannah River National Laboratory', 'oracle', 'ewvl.fa.us8.oraclecloud.com|CX_1'),
  ('SCOR', 'oracle', 'fa-errt-saasfaprod1.fa.ocs.oraclecloud.com|CX_2001'),
  ('SHEIN', 'oracle', 'fa-exjq-saasfaprod1.fa.ocs.oraclecloud.com|SHEIN'),
  ('Tradeweb', 'oracle', 'ecnf.fa.us2.oraclecloud.com|CX'),
  ('Verisk', 'oracle', 'fa-ewmy-saasfaprod1.fa.ocs.oraclecloud.com|CX_1'),
  ('Western Digital', 'smartrecruiters', 'WesternDigital'),
  ('AeroVect', 'smartrecruiters', 'AeroVect'),
  ('Barkback', 'smartrecruiters', 'barkbackLlc'),
  ('BlinqLABS', 'smartrecruiters', 'Blinqlabs'),
  ('Clinical Ink', 'smartrecruiters', 'ClinicalInk'),
  ('Codeage', 'smartrecruiters', 'Codeage'),
  ('Encephalo Investments', 'smartrecruiters', 'EncephaloInvestments'),
  ('Fannie Mae', 'smartrecruiters', 'FannieMae1SB'),
  ('Felix Magazine', 'smartrecruiters', 'LuxeMediaLLC'),
  ('Huck Adventures', 'smartrecruiters', 'HuckAdventures'),
  ('iFLIP4', 'smartrecruiters', 'iFLIP4'),
  ('Inbulks', 'smartrecruiters', 'InbulksCorp'),
  ('InfiniteQuant', 'smartrecruiters', 'InfiniteQuant'),
  ('Interco', 'smartrecruiters', 'Interco'),
  ('KOSTAL Group', 'smartrecruiters', 'KOSTALGroup'),
  ('Lawrence Livermore National Laboratory (LLNL)', 'smartrecruiters', 'LLNL'),
  ('LAXIR', 'smartrecruiters', 'Laxir1'),
  ('Léger', 'smartrecruiters', 'Leger2'),
  ('Northwestern Mutual', 'smartrecruiters', 'NorthwesternMutual'),
  ('RegDesk', 'smartrecruiters', 'RegDeskInc'),
  ('RESPEC', 'smartrecruiters', 'RESPECInc'),
  ('RRS Group', 'smartrecruiters', 'RRSGroup'),
  ('SightCall', 'smartrecruiters', 'SightCall'),
  ('SOCOTEC UK & Ireland', 'smartrecruiters', 'SOCOTECUKIreland'),
  ('University Health Network', 'smartrecruiters', 'UniversityHealthNetwork'),
  ('VWH Capital Management', 'smartrecruiters', 'VWHCapitalManagementLP'),
  ('Zoomifier', 'smartrecruiters', 'CustomShow'),
  ('Dev Technology Group', 'greenhouse', 'devtechnology'),
  ('Geotab', 'greenhouse', 'internshiplist2000'),
  ('HP IQ', 'greenhouse', 'hpiq'),
  ('IXL Learning', 'greenhouse', 'ixllearning'),
  ('K2 Space', 'greenhouse', 'k2spacecorporation'),
  ('Machina Labs', 'lever', 'MachinaLabs'),
  ('Major League Baseball', 'greenhouse', 'baltimoreorioles'),
  ('Michael Baker International', 'oracle', 'ebxs.fa.us2.oraclecloud.com|CX_2'),
  ('Northwood Space', 'ashby', 'NorthwoodSpace'),
  ('Pella', 'oracle', 'ebgj.fa.us2.oraclecloud.com|CX_1'),
  ('Pluralis Research', 'ashby', 'pluralis-research'),
  ('Riverside Natural Foods', 'greenhouse', 'riversidenaturalfoodsltd'),
  ('Schroders', 'oracle', 'ekbq.fa.em2.oraclecloud.com|CX_2'),
  ('Thea Energy', 'lever', 'thea.energy'),
  ('Waymo', 'greenhouse', 'waymo'),
  ('WhatNot', 'ashby', 'whatnot'),
  ('Armadin', 'ashby', 'armadin'),
  ('Cheiron', 'ashby', 'cheiron'),
  ('Formlabs', 'greenhouse', 'formlabs'),
  ('General Dynamics UK', 'smartrecruiters', 'GDMSI'),
  ('Hormel Foods', 'oracle', 'ekkh.fa.us2.oraclecloud.com|CX_2002'),
  ('Valon', 'ashby', 'Valon'),
  ('Williams Racing', 'smartrecruiters', 'WilliamsRacing'),
  ('Winsupply', 'smartrecruiters', 'Winsupply1'),
  ('Acumatica', 'smartrecruiters', 'Acumatica'),
  ('Akuna Capital University', 'greenhouse', 'akunacapital'),
  ('Albedo', 'greenhouse', 'albedo'),
  ('Arconic', 'oracle', 'hdnn.fa.us6.oraclecloud.com|CX'),
  ('Axle', 'smartrecruiters', 'AxleInformaticsLLC'),
  ('Brave', 'greenhouse', 'brave'),
  ('Clinton Foundation', 'greenhouse', 'clintonfoundation'),
  ('Contoro', 'ashby', 'contoro'),
  ('Definity Financial', 'oracle', 'hdks.fa.ca2.oraclecloud.com|CX_1'),
  ('Dynamic Catholic', 'lever', 'dynamiccatholic'),
  ('Faraday Future', 'greenhouse', 'faradayfuture'),
  ('FGS Global', 'greenhouse', 'fgsglobal'),
  ('Garner Health', 'greenhouse', 'garnerhealth'),
  ('Loram', 'smartrecruiters', 'Loram1'),
  ('Major League Baseball', 'lever', 'redsox'),
  ('Man Group', 'greenhouse', 'mangroup'),
  ('Mirego', 'lever', 'mirego'),
  ('Niantic Spatial', 'ashby', 'niantic-spatial'),
  ('Odys Aviation', 'ashby', 'odys-aviation'),
  ('Parkdepot', 'lever', 'salesdemo-jr'),
  ('Peak Energy', 'greenhouse', 'peakenergy'),
  ('Primer', 'ashby', 'primer'),
  ('Qualified Health', 'ashby', 'qualified-health-pbc'),
  ('Ramiel Capital', 'ashby', 'ramielcapital'),
  ('Shawbrook', 'smartrecruiters', 'Shawbrook'),
  ('skillz', 'greenhouse', 'skillzinc'),
  ('Skyward', 'smartrecruiters', 'Skyward1'),
  ('Solidigm', 'smartrecruiters', 'Solidigm'),
  ('Symphony', 'greenhouse', 'symphony'),
  ('The Exploration Company', 'ashby', 'the-exploration-company'),
  ('Tutor Intelligence', 'lever', 'tutorintelligence'),
  ('Vaxcyte', 'greenhouse', 'vaxcyte'),
  ('Acron Aviation', 'lever', 'acronaviation'),
  ('AEG', 'greenhouse', 'aegworldwide'),
  ('Allen Control Systems', 'ashby', 'allen-control-systems'),
  ('Amperesand', 'greenhouse', 'amperesand'),
  ('Antares Nuclear', 'ashby', 'Antares'),
  ('Awardco', 'greenhouse', 'awardco'),
  ('Baidu USA', 'greenhouse', 'baidu'),
  ('Barnes & Thornburg', 'ashby', 'barnes'),
  ('Bedrock Robotics', 'ashby', 'bedrock-robotics'),
  ('Charta Health', 'ashby', 'chartahealth'),
  ('Commure', 'ashby', 'Commure'),
  ('CoVar', 'greenhouse', 'covar'),
  ('D2L', 'greenhouse', 'd2l'),
  ('Decagon', 'ashby', 'decagon'),
  ('Domino Data Lab', 'greenhouse', 'dominodatalab'),
  ('DoorDash', 'greenhouse', 'doordashcanada'),
  ('Duolingo', 'greenhouse', 'duolingounirecruitment'),
  ('Duolingo', 'greenhouse', 'duolingo'),
  ('Emergent Labs', 'greenhouse', 'emergentlabsinc'),
  ('EQT Corporation', 'greenhouse', 'eqtcorporation'),
  ('Exegy', 'ashby', 'exegy'),
  ('Fanvue', 'ashby', 'fanvue.com'),
  ('Fortune Brands', 'smartrecruiters', 'FortuneBrands'),
  ('Gallup', 'greenhouse', 'gallup'),
  ('GM financial', 'oracle', 'fa-exvu-saasfaprod1.fa.ocs.oraclecloud.com|CX_1'),
  ('Hex Technologies', 'greenhouse', 'hextechnologies'),
  ('Hometap', 'greenhouse', 'hometapjobs'),
  ('ibotta', 'ashby', 'ibotta'),
  ('Immuta', 'lever', 'immuta'),
  ('incident.io', 'ashby', 'incident'),
  ('Inferact', 'ashby', 'inferact'),
  ('Interstates', 'greenhouse', 'interstates'),
  ('InterSystems', 'greenhouse', 'intersystems'),
  ('Kitware', 'lever', 'kitware'),
  ('Knobelsdorff Enterprises', 'smartrecruiters', 'KnobelsdorffEnterprises'),
  ('Lexington Medical', 'greenhouse', 'lexingtonmedical'),
  ('M3USA', 'smartrecruiters', 'M3USA'),
  ('MegazoneCloud', 'ashby', 'megazone'),
  ('Mill', 'greenhouse', 'mill'),
  ('Nanopath', 'greenhouse', 'nanopathinc'),
  ('National Life', 'greenhouse', 'nationallifeinsurancecompany'),
  ('Netcompany', 'smartrecruiters', 'Netcompany1'),
  ('OpenGov', 'ashby', 'opengov'),
  ('Pace', 'ashby', 'withpace'),
  ('Pacific Fusion', 'greenhouse', 'pacificfusion'),
  ('PressW', 'ashby', 'pressw'),
  ('Protective Life', 'lever', 'protective'),
  ('Revel', 'ashby', 'revel'),
  ('Rilla', 'ashby', 'rilla'),
  ('Semgrep', 'ashby', 'semgrep'),
  ('SEP', 'lever', 'sep'),
  ('Sequence Holdings', 'ashby', 'seqholdings'),
  ('SingleStore', 'greenhouse', 'singlestore'),
  ('SPAICE Technology', 'ashby', 'spaice-tech'),
  ('SpawGlass', 'lever', 'spawglass'),
  ('Superhuman', 'ashby', 'Superhuman Platform Inc'),
  ('Swarm Aero', 'ashby', 'swarmaero'),
  ('Talos', 'ashby', 'Talos-Trading'),
  ('Tanium', 'greenhouse', 'tanium'),
  ('The MJ Companies', 'greenhouse', 'themjcos'),
  ('TTP', 'smartrecruiters', 'TTP1'),
  ('Viam', 'greenhouse', 'viamrobotics'),
  ('Vusion', 'smartrecruiters', 'VusionGroupSA'),
  ('Wabash Valley Power Alliance', 'smartrecruiters', 'WabashValleyPowerAlliance'),
  ('Wellmark', 'smartrecruiters', 'WellmarkInc'),
  ('Workshop', 'greenhouse', 'workshop'),
  ('Xcimer Energy', 'lever', 'xcimer'),
  ('ConductorAI', 'ashby', 'conductorai'),
  ('DatologyAI', 'ashby', 'DatologyAI'),
  ('Fable', 'ashby', 'fable'),
  ('Rothesay', 'greenhouse', 'rothesaygraduates'),
  ('The Brattle Group', 'greenhouse', 'thebrattlegroup'),
  ('Bitmovin', 'greenhouse', 'bitmovin'),
  ('Boston Properties', 'oracle', 'edxn.fa.us2.oraclecloud.com|CX_5001'),
  ('Bracket Bot', 'ashby', 'bracket-bot'),
  ('Collinear AI', 'ashby', 'collinear-ai'),
  ('Coram AI', 'ashby', 'coram-ai'),
  ('Cowboy Space', 'ashby', 'cowboyspace'),
  ('CSC Generation', 'lever', 'cscgeneration-2'),
  ('Grow Therapy', 'ashby', 'grow-therapy'),
  ('Healthesystems', 'greenhouse', 'healthesystems'),
  ('Keenfinity', 'smartrecruiters', 'Keenfinity'),
  ('Lazard', 'oracle', 'icbpjb.fa.ocs.oraclecloud.com|LazardProfessionalCareers'),
  ('Lean TECHniques', 'ashby', 'leantechniques'),
  ('Newham', 'oracle', 'elyq.fa.em3.oraclecloud.com|CX'),
  ('ONE Finance', 'ashby', 'oneapp'),
  ('PrizePicks', 'greenhouse', 'prizepicks'),
  ('Qumulo', 'ashby', 'qumulo'),
  ('Resultant', 'smartrecruiters', 'Resultant'),
  ('Rhoda AI', 'ashby', 'rhoda-ai'),
  ('Rubrik', 'greenhouse', 'rubrik'),
  ('SeatGeek', 'greenhouse', 'seatgeek'),
  ('Udig', 'greenhouse', 'udig'),
  ('Upstart', 'greenhouse', 'upstart'),
  ('William Blair', 'greenhouse', 'williamblair'),
  ('ZipRecruiter', 'greenhouse', 'ziprecruiter'),
  ('Arista Networks', 'smartrecruiters', 'AristaNetworks'),
  ('BGE', 'greenhouse', 'bgeinc'),
  ('BGE', 'greenhouse', 'bgeinccampus'),
  ('Brightstar.AI', 'ashby', 'brightstar-ai'),
  ('Cohen & Steers', 'greenhouse', 'cnssummerassociates'),
  ('Envoy', 'ashby', 'envoy'),
  ('Genesis Molecular AI', 'ashby', 'genesis-molecular-ai'),
  ('GovSignals', 'ashby', 'GovSignals'),
  ('Heven AeroTech', 'greenhouse', 'hevenaerotech'),
  ('Major League Baseball', 'greenhouse', 'clevelandguardiansbops'),
  ('PathAI', 'greenhouse', 'pathai'),
  ('Red Ventures', 'greenhouse', 'redventures')
ON CONFLICT (source, board_token) DO UPDATE SET
  name = EXCLUDED.name,
  updated_at = now();
