import type { CompanyConfig } from "../types.js";

/**
 * Boards verified against each ATS public job API.
 * Greenhouse / Lever / Ashby tokens seeded from Simplify intern-list URLs.
 */
export const companies: CompanyConfig[] = [
  { name: "1-800 Contacts", source: "greenhouse", boardToken: "1800contacts" },
  { name: "10a Labs", source: "greenhouse", boardToken: "10alabs" },
  { name: "10Beauty", source: "greenhouse", boardToken: "10beauty" },
  { name: "60decibelsinc", source: "greenhouse", boardToken: "60decibelsinc" },
  { name: "A Thinking Ape", source: "greenhouse", boardToken: "athinkingape" },
  { name: "Abacus Insights", source: "greenhouse", boardToken: "abacusinsights" },
  { name: "AbelsonTaylor", source: "greenhouse", boardToken: "abelsontaylor" },
  { name: "AccuWeather", source: "greenhouse", boardToken: "accuweather" },
  { name: "ACLU Kentucky", source: "greenhouse", boardToken: "acluinternships" },
  { name: "Ad Council", source: "greenhouse", boardToken: "adcouncil" },
  { name: "Ada", source: "greenhouse", boardToken: "ada18" },
  { name: "Advanced Space", source: "greenhouse", boardToken: "advancedspace" },
  { name: "Aevex Aerospace", source: "greenhouse", boardToken: "aevexaerospace" },
  { name: "Affirm", source: "greenhouse", boardToken: "affirm" },
  { name: "AgWest Farm Credit", source: "greenhouse", boardToken: "agwestfarmcredit" },
  { name: "Airbnb", source: "greenhouse", boardToken: "airbnb" },
  { name: "AirCapture", source: "greenhouse", boardToken: "aircapture" },
  { name: "Alamar Biosciences", source: "greenhouse", boardToken: "alamarbiosciences" },
  { name: "Alarm.com", source: "greenhouse", boardToken: "alarmcom" },
  { name: "ALKU", source: "greenhouse", boardToken: "alku" },
  { name: "Alo Yoga", source: "greenhouse", boardToken: "aloyoga" },
  { name: "AMAROK Security", source: "greenhouse", boardToken: "amarok" },
  { name: "American Institutes for Research", source: "greenhouse", boardToken: "americaninstitutesforresearch" },
  { name: "Amp Robotics", source: "greenhouse", boardToken: "ampsortation" },
  { name: "Anduril", source: "greenhouse", boardToken: "andurilindustries" },
  { name: "Anthropic", source: "greenhouse", boardToken: "anthropic" },
  { name: "Antora Energy", source: "greenhouse", boardToken: "antora" },
  { name: "Apera AI", source: "greenhouse", boardToken: "aperaaiinc" },
  { name: "Apex Companies", source: "greenhouse", boardToken: "apexcompanies" },
  { name: "Appian", source: "greenhouse", boardToken: "appian" },
  { name: "Apptronik", source: "greenhouse", boardToken: "apptronik" },
  { name: "Aquatic Capital Management", source: "greenhouse", boardToken: "aquaticcapitalmanagement" },
  { name: "Arcesium", source: "greenhouse", boardToken: "arcesiumllc" },
  { name: "Archer", source: "greenhouse", boardToken: "archer56" },
  { name: "Arevon", source: "greenhouse", boardToken: "arevonenergyimpltest" },
  { name: "Argmax", source: "greenhouse", boardToken: "argmax" },
  { name: "Armada", source: "greenhouse", boardToken: "armada" },
  { name: "Arvinas", source: "greenhouse", boardToken: "arvinas" },
  { name: "Asana", source: "greenhouse", boardToken: "asana" },
  { name: "Assured Guaranty", source: "greenhouse", boardToken: "assuredguaranty" },
  { name: "Astera Labs", source: "greenhouse", boardToken: "asteraearlycareer2026" },
  { name: "Astera Labs", source: "greenhouse", boardToken: "asteralabs" },
  { name: "Astranis", source: "greenhouse", boardToken: "astranis" },
  { name: "Atlas Energy Solutions", source: "greenhouse", boardToken: "atlassand" },
  { name: "Atoms", source: "greenhouse", boardToken: "cssmerge" },
  { name: "Attentive", source: "greenhouse", boardToken: "attentive" },
  { name: "Auctane", source: "greenhouse", boardToken: "auctane" },
  { name: "Audax Group", source: "greenhouse", boardToken: "audaxgroup" },
  { name: "Authentic", source: "greenhouse", boardToken: "authenticbrandsgroup" },
  { name: "AvePoint", source: "greenhouse", boardToken: "avepoint" },
  { name: "Avride", source: "greenhouse", boardToken: "avride" },
  { name: "Axiomatic AI", source: "greenhouse", boardToken: "axiomaticai" },
  { name: "Axios", source: "greenhouse", boardToken: "axios" },
  { name: "Axon", source: "greenhouse", boardToken: "axon" },
  { name: "Axon", source: "greenhouse", boardToken: "axontalentcommunity" },
  { name: "AXQ Capital", source: "greenhouse", boardToken: "axq" },
  { name: "AXS", source: "greenhouse", boardToken: "axs" },
  { name: "Axsome Therapeutics Inc", source: "greenhouse", boardToken: "axsometherapeutics" },
  { name: "Aypa Power", source: "greenhouse", boardToken: "aypapower" },
  { name: "Babel Street", source: "greenhouse", boardToken: "babelstreet" },
  { name: "BambooHR", source: "greenhouse", boardToken: "bamboohr17" },
  { name: "Bandwidth", source: "greenhouse", boardToken: "bandwidth" },
  { name: "BCG", source: "greenhouse", boardToken: "bcg" },
  { name: "BetterHelp", source: "greenhouse", boardToken: "betterhelpcom" },
  { name: "BillionToOne", source: "greenhouse", boardToken: "billiontoone" },
  { name: "BlackEdge Capital", source: "greenhouse", boardToken: "blackedgecapital" },
  { name: "BlackSky", source: "greenhouse", boardToken: "blacksky" },
  { name: "Block", source: "greenhouse", boardToken: "block" },
  { name: "Blockchain.com", source: "greenhouse", boardToken: "blockchain" },
  { name: "Bloomberg Philanthropies", source: "greenhouse", boardToken: "bloombergdotorg" },
  { name: "Blue Sky Innovators", source: "greenhouse", boardToken: "blueskyinnovators" },
  { name: "BlueLabs Analytics", source: "greenhouse", boardToken: "bluelabsanalyticsinc" },
  { name: "Bluestaq", source: "greenhouse", boardToken: "bluestaq" },
  { name: "Bot Auto", source: "greenhouse", boardToken: "botauto" },
  { name: "Box", source: "greenhouse", boardToken: "boxinc" },
  { name: "Bracebridge Capital", source: "greenhouse", boardToken: "bracebridgecapital" },
  { name: "Breeze Airways", source: "greenhouse", boardToken: "breezeairways" },
  { name: "Brevium", source: "greenhouse", boardToken: "brevium" },
  { name: "BrightAI", source: "greenhouse", boardToken: "brightai" },
  { name: "BTI360", source: "greenhouse", boardToken: "bti36021" },
  { name: "Bugcrowd", source: "greenhouse", boardToken: "bugcrowd" },
  { name: "Businessolver", source: "greenhouse", boardToken: "businessolverinvitationonly" },
  { name: "Calyxo", source: "greenhouse", boardToken: "calyxo" },
  { name: "Cambridge Mobile Telematics", source: "greenhouse", boardToken: "cmt" },
  { name: "Cartesian", source: "greenhouse", boardToken: "cartesiansystems" },
  { name: "Cell Signaling Technology", source: "greenhouse", boardToken: "cellsignalingtechnology79" },
  { name: "Celonis", source: "greenhouse", boardToken: "celonis" },
  { name: "Checkr", source: "greenhouse", boardToken: "checkr" },
  { name: "Chicago Trading Company", source: "greenhouse", boardToken: "chicagotradingcampus" },
  { name: "Chicago Trading Company", source: "greenhouse", boardToken: "ctccampusboard" },
  { name: "Clarity Innovations", source: "greenhouse", boardToken: "clarityinnovates" },
  { name: "CLEAR", source: "greenhouse", boardToken: "clear" },
  { name: "Clearway Energy", source: "greenhouse", boardToken: "clearwayjobs" },
  { name: "Climate Corps", source: "greenhouse", boardToken: "cc" },
  { name: "Clockwork Systems", source: "greenhouse", boardToken: "clockworksystems" },
  { name: "Cloudflare", source: "greenhouse", boardToken: "cloudflare" },
  { name: "CloudKitchens", source: "greenhouse", boardToken: "css" },
  { name: "Cobalt", source: "greenhouse", boardToken: "cobaltio" },
  { name: "Cognitiv", source: "greenhouse", boardToken: "cognitiv" },
  { name: "Cohere Health", source: "greenhouse", boardToken: "coherehealth" },
  { name: "Coinbase", source: "greenhouse", boardToken: "coinbase" },
  { name: "CoLab Software", source: "greenhouse", boardToken: "colabsoftware" },
  { name: "Commvault", source: "greenhouse", boardToken: "commvault" },
  { name: "Compeer Financial", source: "greenhouse", boardToken: "compeerfinancial" },
  { name: "Comstock Companies", source: "greenhouse", boardToken: "comstock" },
  { name: "Concentric", source: "greenhouse", boardToken: "concentric" },
  { name: "Conner Strong & Buckelew", source: "greenhouse", boardToken: "connerstrongbuckelew" },
  { name: "Constant Contact", source: "greenhouse", boardToken: "constantcontact" },
  { name: "Construction Resources", source: "greenhouse", boardToken: "constructionresources" },
  { name: "Correlation One", source: "greenhouse", boardToken: "correlationone" },
  { name: "Correlation One", source: "greenhouse", boardToken: "expertnetwork" },
  { name: "Cortland", source: "greenhouse", boardToken: "cortland" },
  { name: "Cresta", source: "greenhouse", boardToken: "cresta" },
  { name: "Critical Mass", source: "greenhouse", boardToken: "criticalmass" },
  { name: "Custom Computer Specialists", source: "greenhouse", boardToken: "customcomputerspecialists" },
  { name: "Dark Wolf Solutions", source: "greenhouse", boardToken: "darkwolfsolutions" },
  { name: "Databricks", source: "greenhouse", boardToken: "databricks" },
  { name: "Defense Unicorns", source: "greenhouse", boardToken: "defenseunicorns" },
  { name: "DESIGNME Hair", source: "greenhouse", boardToken: "designmehair" },
  { name: "Detroit Lions", source: "greenhouse", boardToken: "detroitlions" },
  { name: "DevRev", source: "greenhouse", boardToken: "devrev" },
  { name: "DH Pace", source: "greenhouse", boardToken: "dhpace" },
  { name: "DiDi Global", source: "greenhouse", boardToken: "didi" },
  { name: "Digs", source: "greenhouse", boardToken: "digs" },
  { name: "Diligent Corporation", source: "greenhouse", boardToken: "diligentcorporation" },
  { name: "Discord", source: "greenhouse", boardToken: "discord" },
  { name: "Disney", source: "greenhouse", boardToken: "disney" },
  { name: "Doctors Without Borders", source: "greenhouse", boardToken: "msfcareers" },
  { name: "Docugami", source: "greenhouse", boardToken: "docugami" },
  { name: "DoorDash", source: "greenhouse", boardToken: "doordashusa" },
  { name: "Dorsia", source: "greenhouse", boardToken: "dorsia" },
  { name: "Double Good", source: "greenhouse", boardToken: "doublegood" },
  { name: "DoubleVerify", source: "greenhouse", boardToken: "doubleverify" },
  { name: "Doximity", source: "greenhouse", boardToken: "doximity" },
  { name: "DriveWealth", source: "greenhouse", boardToken: "drivewealth" },
  { name: "Dropbox", source: "greenhouse", boardToken: "dropbox" },
  { name: "DRW", source: "greenhouse", boardToken: "drweng" },
  { name: "DRW", source: "greenhouse", boardToken: "drwuniversityjobs" },
  { name: "DV Trading", source: "greenhouse", boardToken: "dvtrading" },
  { name: "EarnIn", source: "greenhouse", boardToken: "earnin" },
  { name: "Echodyne", source: "greenhouse", boardToken: "echodynecorp" },
  { name: "edmentum", source: "greenhouse", boardToken: "edmentum" },
  { name: "Efficient Computer", source: "greenhouse", boardToken: "efficientcomputer" },
  { name: "Eikon Therapeutics", source: "greenhouse", boardToken: "eikontherapeutics" },
  { name: "Elastic", source: "greenhouse", boardToken: "elastic" },
  { name: "Elevations Credit Union", source: "greenhouse", boardToken: "elevationscreditunion" },
  { name: "EnergyHub", source: "greenhouse", boardToken: "energyhub" },
  { name: "Eudia", source: "greenhouse", boardToken: "eudia" },
  { name: "Eulerity", source: "greenhouse", boardToken: "eulerity" },
  { name: "Everlaw", source: "greenhouse", boardToken: "everlaw" },
  { name: "Evolver", source: "greenhouse", boardToken: "evolver" },
  { name: "Excel Sports Management", source: "greenhouse", boardToken: "excelsportsmanagement" },
  { name: "ExodusPoint", source: "greenhouse", boardToken: "exoduspoint" },
  { name: "ezCater", source: "greenhouse", boardToken: "ezcaterinc" },
  { name: "F. Schumacher & Co.", source: "greenhouse", boardToken: "fschumacherco" },
  { name: "Faire", source: "greenhouse", boardToken: "faire" },
  { name: "Fairlife", source: "greenhouse", boardToken: "fairlife" },
  { name: "Fever Up", source: "greenhouse", boardToken: "feverup" },
  { name: "Figma", source: "greenhouse", boardToken: "figma" },
  { name: "Figure", source: "greenhouse", boardToken: "figure" },
  { name: "Figure", source: "greenhouse", boardToken: "figureai" },
  { name: "Financial Technology Partners", source: "greenhouse", boardToken: "financialtechnologypartners" },
  { name: "Five Rings Capital", source: "greenhouse", boardToken: "fiveringsllc" },
  { name: "Flagship Pioneering", source: "greenhouse", boardToken: "flagshippioneeringinc" },
  { name: "Flagship Pioneering", source: "greenhouse", boardToken: "fspco-op012325" },
  { name: "Flow Traders", source: "greenhouse", boardToken: "flowtraders" },
  { name: "Focus Financial Partners", source: "greenhouse", boardToken: "focusfinancialpartners" },
  { name: "Foley Hoag", source: "greenhouse", boardToken: "foleyhoag" },
  { name: "Formic", source: "greenhouse", boardToken: "formic" },
  { name: "Fortera", source: "greenhouse", boardToken: "forteracorporation" },
  { name: "Forward Networks", source: "greenhouse", boardToken: "forwardnetworks" },
  { name: "Four Hands", source: "greenhouse", boardToken: "fourhands" },
  { name: "FourKites", source: "greenhouse", boardToken: "fourkites" },
  { name: "Freeform", source: "greenhouse", boardToken: "freeformfuturecorp" },
  { name: "Fussball Club Cincinnati LLC (“FC Cincinnati”)", source: "greenhouse", boardToken: "fccincinnati" },
  { name: "Galaxy", source: "greenhouse", boardToken: "galaxydigitalservices" },
  { name: "Gametime", source: "greenhouse", boardToken: "gametimeunited" },
  { name: "Garda Capital Partners", source: "greenhouse", boardToken: "gardacp" },
  { name: "GCM Grosvenor", source: "greenhouse", boardToken: "gcmgrosvenor" },
  { name: "Gelber Group", source: "greenhouse", boardToken: "gelbergroup" },
  { name: "Gelber Group", source: "greenhouse", boardToken: "gelberhandshake" },
  { name: "Gemini", source: "greenhouse", boardToken: "gemini" },
  { name: "General Atlantic", source: "greenhouse", boardToken: "generalatlantic" },
  { name: "General Matter", source: "greenhouse", boardToken: "generalmatter" },
  { name: "Geneva Trading", source: "greenhouse", boardToken: "genevatrading" },
  { name: "GenScript", source: "greenhouse", boardToken: "genscript" },
  { name: "Gensyn", source: "greenhouse", boardToken: "gensyn" },
  { name: "Geotab", source: "greenhouse", boardToken: "geotab" },
  { name: "Ginkgo Bioworks", source: "greenhouse", boardToken: "ginkgobioworks" },
  { name: "Globalization Partners", source: "greenhouse", boardToken: "globalizationpartners" },
  { name: "GlossGenius", source: "greenhouse", boardToken: "glossgenius" },
  { name: "Glydways", source: "greenhouse", boardToken: "glydways" },
  { name: "GoDaddy", source: "greenhouse", boardToken: "eventsandinterns" },
  { name: "GoFundMe", source: "greenhouse", boardToken: "gofundme" },
  { name: "Golden Pet Brands", source: "greenhouse", boardToken: "goldenpetbrands" },
  { name: "Graphcore", source: "greenhouse", boardToken: "graphcore" },
  { name: "Grassroots Analytics", source: "greenhouse", boardToken: "grassrootsanalytics" },
  { name: "Greenworks", source: "greenhouse", boardToken: "greenworkssunriseglobalmarketing" },
  { name: "GRVTY", source: "greenhouse", boardToken: "grvty" },
  { name: "GSD&M", source: "greenhouse", boardToken: "gsdm" },
  { name: "Guidepoint", source: "greenhouse", boardToken: "guidepoint" },
  { name: "Gusto", source: "greenhouse", boardToken: "gusto" },
  { name: "Haize Labs", source: "greenhouse", boardToken: "haizelabs" },
  { name: "Harbinger Motors", source: "greenhouse", boardToken: "harbingermotors" },
  { name: "Haven Studios", source: "greenhouse", boardToken: "haven" },
  { name: "Health-E Commerce", source: "greenhouse", boardToken: "fsastorecom" },
  { name: "HeartFlow", source: "greenhouse", boardToken: "heartflowinc" },
  { name: "HELLBENDER", source: "greenhouse", boardToken: "hellbenderinc" },
  { name: "HeyGen", source: "greenhouse", boardToken: "heygen" },
  { name: "Hive Financial Systems", source: "greenhouse", boardToken: "hivefinancialsystems" },
  { name: "Hone Health", source: "greenhouse", boardToken: "honehealth" },
  { name: "Horace Mann", source: "greenhouse", boardToken: "horacemannservicecorporation" },
  { name: "Horizon Industries", source: "greenhouse", boardToken: "horizonindustrieslimited" },
  { name: "HPR (Hyannis Port Research)", source: "greenhouse", boardToken: "hyannisportresearch" },
  { name: "HubSpot", source: "greenhouse", boardToken: "hubspot" },
  { name: "Hudl", source: "greenhouse", boardToken: "hudl" },
  { name: "HumanSignal", source: "greenhouse", boardToken: "humansignal" },
  { name: "ID.me", source: "greenhouse", boardToken: "idmeuniversityrecruiting" },
  { name: "IEM", source: "greenhouse", boardToken: "industrialelectricmanufacturing" },
  { name: "IMC Trading", source: "greenhouse", boardToken: "imc" },
  { name: "impact.com", source: "greenhouse", boardToken: "impact" },
  { name: "Impinj", source: "greenhouse", boardToken: "impinjexternal" },
  { name: "Impiricus", source: "greenhouse", boardToken: "impiricus" },
  { name: "Incident IQ", source: "greenhouse", boardToken: "incidentiq" },
  { name: "Inizio", source: "greenhouse", boardToken: "inizio" },
  { name: "Innodata", source: "greenhouse", boardToken: "innodatainc" },
  { name: "Inspire Medical Systems", source: "greenhouse", boardToken: "inspiremedicalsystemsinc" },
  { name: "Instacart", source: "greenhouse", boardToken: "instacart" },
  { name: "InstaLILY", source: "greenhouse", boardToken: "instalilyai" },
  { name: "Instawork", source: "greenhouse", boardToken: "instawork" },
  { name: "Instead", source: "greenhouse", boardToken: "instead" },
  { name: "Integra FEC", source: "greenhouse", boardToken: "integra" },
  { name: "Integra FEC", source: "greenhouse", boardToken: "integrainterns" },
  { name: "Intrinsic", source: "greenhouse", boardToken: "intrinsicrobotics" },
  { name: "Invisible Technologies AI", source: "greenhouse", boardToken: "agency" },
  { name: "Iovance Biotherapeutics", source: "greenhouse", boardToken: "iovancebiotherapeutics" },
  { name: "iSpot.tv", source: "greenhouse", boardToken: "ispottv" },
  { name: "Ivalua", source: "greenhouse", boardToken: "ivalua" },
  { name: "IVX Health", source: "greenhouse", boardToken: "ivxhealth" },
  { name: "Jane Street", source: "greenhouse", boardToken: "janestreet" },
  { name: "Jencap", source: "greenhouse", boardToken: "jencapinc" },
  { name: "Jumio", source: "greenhouse", boardToken: "jumio" },
  { name: "Juvare", source: "greenhouse", boardToken: "juvare" },
  { name: "Kairos Power", source: "greenhouse", boardToken: "kairospower" },
  { name: "Kapitus", source: "greenhouse", boardToken: "kapitus" },
  { name: "Kargo", source: "greenhouse", boardToken: "kargo" },
  { name: "Kensington", source: "greenhouse", boardToken: "kensingtontours" },
  { name: "Kikoff", source: "greenhouse", boardToken: "kikoff" },
  { name: "Klaviyo", source: "greenhouse", boardToken: "klaviyocampus" },
  { name: "KnowBe4", source: "greenhouse", boardToken: "knowbe4" },
  { name: "Koddi", source: "greenhouse", boardToken: "koddi" },
  { name: "Kodiak Robotics", source: "greenhouse", boardToken: "kodiak" },
  { name: "KRAFTON", source: "greenhouse", boardToken: "studiokraftonboard" },
  { name: "Kroll Bond Rating Agency", source: "greenhouse", boardToken: "krollbondratingagency" },
  { name: "Labelbox", source: "greenhouse", boardToken: "labelbox" },
  { name: "Lasko Products", source: "greenhouse", boardToken: "laskoproducts" },
  { name: "Later", source: "greenhouse", boardToken: "later" },
  { name: "LaunchDarkly", source: "greenhouse", boardToken: "launchdarkly" },
  { name: "Layer Health", source: "greenhouse", boardToken: "layerhealth" },
  { name: "League", source: "greenhouse", boardToken: "leagueinc" },
  { name: "Legend Biotech", source: "greenhouse", boardToken: "legendcareers" },
  { name: "LG Electronics", source: "greenhouse", boardToken: "lgelectronics" },
  { name: "LHV Bank", source: "greenhouse", boardToken: "lhvuk" },
  { name: "Lightmatter", source: "greenhouse", boardToken: "lightmatter" },
  { name: "Lightspeed Systems", source: "greenhouse", boardToken: "lightspeedsystems" },
  { name: "Lila Sciences", source: "greenhouse", boardToken: "lilasciences" },
  { name: "Locus Robotics", source: "greenhouse", boardToken: "locusrobotics" },
  { name: "LogicGate", source: "greenhouse", boardToken: "logicgate" },
  { name: "Lucid Bots", source: "greenhouse", boardToken: "lucidbots" },
  { name: "Lucid Motors", source: "greenhouse", boardToken: "lucidmotors" },
  { name: "Lumos", source: "greenhouse", boardToken: "lumosfiber" },
  { name: "Lunar Energy", source: "greenhouse", boardToken: "lunarenergy" },
  { name: "Lyft", source: "greenhouse", boardToken: "lyft" },
  { name: "Madison Energy Infrastructure", source: "greenhouse", boardToken: "madisonenergyinfrastructure" },
  { name: "Major League Baseball", source: "greenhouse", boardToken: "philliesbaseballoperations" },
  { name: "Marqeta", source: "greenhouse", boardToken: "mqreferrals" },
  { name: "Marshall Wace", source: "greenhouse", boardToken: "mwinternshipprogram" },
  { name: "Maven Securities", source: "greenhouse", boardToken: "emergingtalent" },
  { name: "Maven Securities", source: "greenhouse", boardToken: "mavensecuritiesholdingltd" },
  { name: "Maybell Quantum Industries", source: "greenhouse", boardToken: "maybellquantum" },
  { name: "McKinney", source: "greenhouse", boardToken: "jobsmckinneycom" },
  { name: "McMaster-Carr", source: "greenhouse", boardToken: "mcmastercarr" },
  { name: "MedElite", source: "greenhouse", boardToken: "medelitellc" },
  { name: "Medical Informatics Engineering", source: "greenhouse", boardToken: "medicalinformaticsengineering" },
  { name: "MEMIC", source: "greenhouse", boardToken: "memic" },
  { name: "Mercury", source: "greenhouse", boardToken: "mercury" },
  { name: "MERGE", source: "greenhouse", boardToken: "mergeworld" },
  { name: "Meridian Partners", source: "greenhouse", boardToken: "morsecorpcoop" },
  { name: "Meriton", source: "greenhouse", boardToken: "meriton" },
  { name: "MerQube", source: "greenhouse", boardToken: "merqube" },
  { name: "MetOx International", source: "greenhouse", boardToken: "metoxinternationalinc" },
  { name: "Minitab", source: "greenhouse", boardToken: "minitab" },
  { name: "Mobilityware", source: "greenhouse", boardToken: "mobilityware" },
  { name: "Moment Energy", source: "greenhouse", boardToken: "momentenergy" },
  { name: "MongoDB", source: "greenhouse", boardToken: "mongodb" },
  { name: "mthree", source: "greenhouse", boardToken: "mthreerecruitingportal" },
  { name: "Muon Space", source: "greenhouse", boardToken: "muonspace" },
  { name: "National Information Solutions Cooperative (NISC)", source: "greenhouse", boardToken: "nisc" },
  { name: "National Information Solutions Cooperative (NISC)", source: "greenhouse", boardToken: "testnisc" },
  { name: "Neo4j", source: "greenhouse", boardToken: "neo4j" },
  { name: "Neuralink", source: "greenhouse", boardToken: "neuralink" },
  { name: "NewsBreak", source: "greenhouse", boardToken: "newsbreak" },
  { name: "Newsela", source: "greenhouse", boardToken: "newsela" },
  { name: "Newton Research", source: "greenhouse", boardToken: "newtonresearch" },
  { name: "Nex", source: "greenhouse", boardToken: "nex" },
  { name: "NICE", source: "greenhouse", boardToken: "nice" },
  { name: "Nimble Gravity", source: "greenhouse", boardToken: "nimblegravity" },
  { name: "Nooks", source: "greenhouse", boardToken: "nooks" },
  { name: "Northspyre", source: "greenhouse", boardToken: "northspyre" },
  { name: "Notability", source: "greenhouse", boardToken: "gingerlabsinc" },
  { name: "NPR", source: "greenhouse", boardToken: "nationalpublicradioinc" },
  { name: "OBE", source: "greenhouse", boardToken: "oldcastlebuildingenvelope" },
  { name: "Obsidian Security", source: "greenhouse", boardToken: "obsidiansecurity" },
  { name: "OceanX", source: "greenhouse", boardToken: "oceanx" },
  { name: "Octaura", source: "greenhouse", boardToken: "octaura" },
  { name: "OfferUp", source: "greenhouse", boardToken: "offerup" },
  { name: "OH.io", source: "greenhouse", boardToken: "ohio" },
  { name: "Okta", source: "greenhouse", boardToken: "okta" },
  { name: "Olsson", source: "greenhouse", boardToken: "olsson" },
  { name: "Omnicom Health", source: "greenhouse", boardToken: "omnicomhealth" },
  { name: "Onapsis", source: "greenhouse", boardToken: "onapsis" },
  { name: "Open Farm Pet", source: "greenhouse", boardToken: "openfarminc" },
  { name: "OpenTable", source: "greenhouse", boardToken: "opentable" },
  { name: "Optiver", source: "greenhouse", boardToken: "optiverprivate" },
  { name: "Optiver", source: "greenhouse", boardToken: "tradingacademy2025" },
  { name: "Orennia", source: "greenhouse", boardToken: "orennia" },
  { name: "OTR Solutions", source: "greenhouse", boardToken: "otrcapital1" },
  { name: "Oura", source: "greenhouse", boardToken: "oura" },
  { name: "Pacvue", source: "greenhouse", boardToken: "pacvue" },
  { name: "Pagaya Investments", source: "greenhouse", boardToken: "pagaya" },
  { name: "Palmetto Clean Technology", source: "greenhouse", boardToken: "palmettocleantech" },
  { name: "Parachute Health", source: "greenhouse", boardToken: "parachutehealth" },
  { name: "Parallel Systems", source: "greenhouse", boardToken: "parallel" },
  { name: "PatientPoint", source: "greenhouse", boardToken: "patientpoint" },
  { name: "PDT Partners", source: "greenhouse", boardToken: "pdtpartners" },
  { name: "Pendar Technologies", source: "greenhouse", boardToken: "pendartechnologies" },
  { name: "Per Scholas", source: "greenhouse", boardToken: "perscholashires" },
  { name: "Perpay", source: "greenhouse", boardToken: "perpay" },
  { name: "Phaidra", source: "greenhouse", boardToken: "phaidra" },
  { name: "Phamily", source: "greenhouse", boardToken: "jobsatphamily" },
  { name: "Phoenix Contact", source: "greenhouse", boardToken: "phoenixcontact" },
  { name: "PhysicsX", source: "greenhouse", boardToken: "physicsx" },
  { name: "Piaggio Fast Forward", source: "greenhouse", boardToken: "piaggiofastforward" },
  { name: "Pinterest", source: "greenhouse", boardToken: "pinterest" },
  { name: "Planet", source: "greenhouse", boardToken: "planetlabs" },
  { name: "PlanetScale", source: "greenhouse", boardToken: "planetscale" },
  { name: "PlayStation", source: "greenhouse", boardToken: "waterloocoop" },
  { name: "PLS", source: "greenhouse", boardToken: "plscareers" },
  { name: "PMG", source: "greenhouse", boardToken: "pmg" },
  { name: "Podium", source: "greenhouse", boardToken: "podium81" },
  { name: "Point C", source: "greenhouse", boardToken: "pointc" },
  { name: "Point72", source: "greenhouse", boardToken: "point72" },
  { name: "PolyAI", source: "greenhouse", boardToken: "polyai" },
  { name: "Postman", source: "greenhouse", boardToken: "postman" },
  { name: "Practising Law Institute", source: "greenhouse", boardToken: "practisinglawinstitute" },
  { name: "Praxent", source: "greenhouse", boardToken: "praxent" },
  { name: "Premier Automation", source: "greenhouse", boardToken: "premierautomation" },
  { name: "Presence", source: "greenhouse", boardToken: "presencelearning" },
  { name: "Profluent", source: "greenhouse", boardToken: "profluent" },
  { name: "Prolaio", source: "greenhouse", boardToken: "prolaio" },
  { name: "Prophet", source: "greenhouse", boardToken: "prophet" },
  { name: "Pure Storage", source: "greenhouse", boardToken: "purestorage" },
  { name: "QGenda", source: "greenhouse", boardToken: "qgenda" },
  { name: "QuEra Computing", source: "greenhouse", boardToken: "queracomputinginc" },
  { name: "RA Capital Management", source: "greenhouse", boardToken: "racapitalmanagementllc" },
  { name: "Rackner", source: "greenhouse", boardToken: "rackner" },
  { name: "Radix Trading", source: "greenhouse", boardToken: "radixuniversity" },
  { name: "Readystate Asset Management", source: "greenhouse", boardToken: "readystate" },
  { name: "Realtor.com", source: "greenhouse", boardToken: "rdccareers" },
  { name: "Reddit", source: "greenhouse", boardToken: "reddit" },
  { name: "Redwood Materials", source: "greenhouse", boardToken: "redwoodmaterials" },
  { name: "Relay", source: "greenhouse", boardToken: "relaypro" },
  { name: "Rexford Industrial", source: "greenhouse", boardToken: "rexfordindustrial" },
  { name: "RF-SMART", source: "greenhouse", boardToken: "rfsmart" },
  { name: "Rhombus Power", source: "greenhouse", boardToken: "rhombuspower" },
  { name: "Rise8", source: "greenhouse", boardToken: "rise8" },
  { name: "Robinhood", source: "greenhouse", boardToken: "robinhood" },
  { name: "RoboForce", source: "greenhouse", boardToken: "roboforce" },
  { name: "Rocket Lab USA", source: "greenhouse", boardToken: "rocketlab" },
  { name: "Rocket Lawyer", source: "greenhouse", boardToken: "rocketlawyer" },
  { name: "RTW Investments", source: "greenhouse", boardToken: "rtwinvestments" },
  { name: "Rugged Robotics", source: "greenhouse", boardToken: "ruggedrobotics" },
  { name: "Sage", source: "greenhouse", boardToken: "sage49" },
  { name: "Salient Motion", source: "greenhouse", boardToken: "salientmotion" },
  { name: "SALT XC", source: "greenhouse", boardToken: "saltxc" },
  { name: "Samaya", source: "greenhouse", boardToken: "samayaai" },
  { name: "Samsung", source: "greenhouse", boardToken: "samsungsemiconductor" },
  { name: "Samsung Research America", source: "greenhouse", boardToken: "samsungresearchamericainternship" },
  { name: "SanMar", source: "greenhouse", boardToken: "sanmar" },
  { name: "Scale AI", source: "greenhouse", boardToken: "scaleai" },
  { name: "Schonfeld", source: "greenhouse", boardToken: "schonfeld" },
  { name: "SchoolMint", source: "greenhouse", boardToken: "schoolmint" },
  { name: "Scopely", source: "greenhouse", boardToken: "scopely" },
  { name: "Scout Motors", source: "greenhouse", boardToken: "scoutmotors" },
  { name: "Seurat Technologies", source: "greenhouse", boardToken: "seurat" },
  { name: "Seven Research", source: "greenhouse", boardToken: "sevenresearch" },
  { name: "Sezzle", source: "greenhouse", boardToken: "sezzle" },
  { name: "SharkNinja", source: "greenhouse", boardToken: "sharkninjaoperatingllc" },
  { name: "SHEIN", source: "greenhouse", boardToken: "shein" },
  { name: "Sigma Computing", source: "greenhouse", boardToken: "sigmacomputing" },
  { name: "Signifyd", source: "greenhouse", boardToken: "signifyd95" },
  { name: "Sila Nanotechnologies", source: "greenhouse", boardToken: "silananotechnologies" },
  { name: "Simple Technology Solutions", source: "greenhouse", boardToken: "simpletechnologysolutions" },
  { name: "SK hynix", source: "greenhouse", boardToken: "skhynixamerica" },
  { name: "Skyryse", source: "greenhouse", boardToken: "skyryse" },
  { name: "Smartly.io", source: "greenhouse", boardToken: "smartlyio" },
  { name: "Snorkel AI", source: "greenhouse", boardToken: "snorkelai" },
  { name: "Solid Power", source: "greenhouse", boardToken: "solidpower" },
  { name: "Sonatus", source: "greenhouse", boardToken: "sonatus" },
  { name: "Sono Bello", source: "greenhouse", boardToken: "sonobello" },
  { name: "SonoThera", source: "greenhouse", boardToken: "sonothera" },
  { name: "Sony Interactive Entertainment", source: "greenhouse", boardToken: "sonyinteractiveentertainmentglobal" },
  { name: "Space Kinetic", source: "greenhouse", boardToken: "spacekinetic" },
  { name: "SpaceX", source: "greenhouse", boardToken: "spacex" },
  { name: "Sparksoft", source: "greenhouse", boardToken: "sparksoftcorporation" },
  { name: "SpecterOps", source: "greenhouse", boardToken: "specterops" },
  { name: "Speechmatics", source: "greenhouse", boardToken: "speechmatics" },
  { name: "SpyCloud", source: "greenhouse", boardToken: "spycloud" },
  { name: "Starburst", source: "greenhouse", boardToken: "starburst" },
  { name: "StockX", source: "greenhouse", boardToken: "stockx" },
  { name: "STR", source: "greenhouse", boardToken: "systemstechnologyresearch" },
  { name: "Strand Therapeutics", source: "greenhouse", boardToken: "strandtherapeutics" },
  { name: "Strata Decision Technology", source: "greenhouse", boardToken: "stratacareers" },
  { name: "Stripe", source: "greenhouse", boardToken: "stripe" },
  { name: "SuccessKPI", source: "greenhouse", boardToken: "successkpiinc" },
  { name: "SupplyHouse.com", source: "greenhouse", boardToken: "supplyhouse" },
  { name: "Syska Hennessy Group", source: "greenhouse", boardToken: "syskahennessy" },
  { name: "Tastylive", source: "greenhouse", boardToken: "tastylive" },
  { name: "tastytrade", source: "greenhouse", boardToken: "tastytrade" },
  { name: "Tatari", source: "greenhouse", boardToken: "tatari" },
  { name: "Technergetics", source: "greenhouse", boardToken: "technergetics" },
  { name: "Tecovas", source: "greenhouse", boardToken: "tecovas" },
  { name: "Tenon", source: "greenhouse", boardToken: "tenon" },
  { name: "Tenstorrent", source: "greenhouse", boardToken: "tenstorrentuniversity" },
  { name: "Terran Orbital", source: "greenhouse", boardToken: "terranorbitalcorporation" },
  { name: "The Allen Institute for AI", source: "greenhouse", boardToken: "thealleninstitute" },
  { name: "The Health Management Academy", source: "greenhouse", boardToken: "thehealthmanagementacademy" },
  { name: "The New York Times", source: "greenhouse", boardToken: "thenewyorktimes" },
  { name: "The Nuclear Company", source: "greenhouse", boardToken: "thenuclearcompany" },
  { name: "The Trade Desk", source: "greenhouse", boardToken: "thetradedesk" },
  { name: "The Weather Company", source: "greenhouse", boardToken: "theweathercompany" },
  { name: "Together AI", source: "greenhouse", boardToken: "togetherai" },
  { name: "Torc Robotics", source: "greenhouse", boardToken: "torcrobotics" },
  { name: "Toshiba Global Commerce", source: "greenhouse", boardToken: "toshibaglobalcommercesolutions" },
  { name: "TransMarket Group", source: "greenhouse", boardToken: "transmarketgroup" },
  { name: "Trexon", source: "greenhouse", boardToken: "tpcengineeringholdingsllc" },
  { name: "TribalScale", source: "greenhouse", boardToken: "tribalscale" },
  { name: "TripArc", source: "greenhouse", boardToken: "triparc" },
  { name: "True Anomaly", source: "greenhouse", boardToken: "trueanomalyinc" },
  { name: "Trumid", source: "greenhouse", boardToken: "trumid" },
  { name: "Truveta", source: "greenhouse", boardToken: "truveta" },
  { name: "Tubi", source: "greenhouse", boardToken: "tubitv" },
  { name: "Twilio", source: "greenhouse", boardToken: "twilio" },
  { name: "Two Six Technologies", source: "greenhouse", boardToken: "twosixtechnologies" },
  { name: "Typeface", source: "greenhouse", boardToken: "typeface" },
  { name: "Uber Freight", source: "greenhouse", boardToken: "uberfreight" },
  { name: "Udemy", source: "greenhouse", boardToken: "udemybedi" },
  { name: "Ultima Genomics", source: "greenhouse", boardToken: "ultimagenomics" },
  { name: "UnitedMasters", source: "greenhouse", boardToken: "unitedmasterstranslation" },
  { name: "University of Virginia Investment Management Company (UVIMCO)", source: "greenhouse", boardToken: "uvimco" },
  { name: "Upstream USA", source: "greenhouse", boardToken: "upstreamusa" },
  { name: "USAFacts", source: "greenhouse", boardToken: "usafacts" },
  { name: "Varda Space", source: "greenhouse", boardToken: "vardaspace" },
  { name: "Veeam Software", source: "greenhouse", boardToken: "veeamsoftware" },
  { name: "Vera Institute of Justice", source: "greenhouse", boardToken: "verainstituteofjustice" },
  { name: "Vercel", source: "greenhouse", boardToken: "vercel" },
  { name: "Verisign", source: "greenhouse", boardToken: "verisign" },
  { name: "Verkada", source: "greenhouse", boardToken: "verkada" },
  { name: "Vestwell", source: "greenhouse", boardToken: "vestwell" },
  { name: "Viking Global", source: "greenhouse", boardToken: "vikingglobalinvestors" },
  { name: "Virtru", source: "greenhouse", boardToken: "virtru" },
  { name: "Virtu Financial", source: "greenhouse", boardToken: "virtu" },
  { name: "Vise", source: "greenhouse", boardToken: "viseai" },
  { name: "Visier Solutions", source: "greenhouse", boardToken: "visiersolutionsinc" },
  { name: "Vixxo", source: "greenhouse", boardToken: "vixxo" },
  { name: "Voloridge", source: "greenhouse", boardToken: "voloridgeinvestmentmanagement" },
  { name: "Voyager Technologies", source: "greenhouse", boardToken: "voyagertechnologiesinc" },
  { name: "VSC Fire & Security", source: "greenhouse", boardToken: "vscfiresecurityinc" },
  { name: "Vulcan Elements", source: "greenhouse", boardToken: "vulcanelements" },
  { name: "Walleye Capital", source: "greenhouse", boardToken: "walleyecapital-external-students" },
  { name: "Wasabi Technologies", source: "greenhouse", boardToken: "wasabi" },
  { name: "Weiss Asset Management", source: "greenhouse", boardToken: "weissassetmanagement" },
  { name: "Wheely", source: "greenhouse", boardToken: "wheely" },
  { name: "WhiteWater Midstream", source: "greenhouse", boardToken: "whitewatermidstream" },
  { name: "Workato", source: "greenhouse", boardToken: "workato" },
  { name: "Workstream", source: "greenhouse", boardToken: "workstream" },
  { name: "World Surf League", source: "greenhouse", boardToken: "worldsurfleague" },
  { name: "WPP Media", source: "greenhouse", boardToken: "wppmedia" },
  { name: "Wurl", source: "greenhouse", boardToken: "wurljobs" },
  { name: "Xaira Therapeutics", source: "greenhouse", boardToken: "xairatherapeutics" },
  { name: "Xantium", source: "greenhouse", boardToken: "xantium" },
  { name: "Xebia", source: "greenhouse", boardToken: "xebiausa" },
  { name: "XPENG Motors", source: "greenhouse", boardToken: "xpengmotors" },
  { name: "XTX Markets", source: "greenhouse", boardToken: "xtxmarketstechnologies" },
  { name: "Yes Energy", source: "greenhouse", boardToken: "yesenergy" },
  { name: "YOU.com", source: "greenhouse", boardToken: "youcom" },
  { name: "Zocdoc", source: "greenhouse", boardToken: "zocdoc" },
  { name: "Zone 5 Technologies", source: "greenhouse", boardToken: "zone5technologies" },
  { name: "Zscaler", source: "greenhouse", boardToken: "zscaler" },
  { name: "Acceldata", source: "lever", boardToken: "acceldata" },
  { name: "Achievers", source: "lever", boardToken: "achievers" },
  { name: "Actian", source: "lever", boardToken: "actian" },
  { name: "Age of Learning", source: "lever", boardToken: "aofl" },
  { name: "AHEAD", source: "lever", boardToken: "thinkahead" },
  { name: "Aledade", source: "lever", boardToken: "aledade" },
  { name: "Alertus Technologies", source: "lever", boardToken: "alertus" },
  { name: "Allegiant Air", source: "lever", boardToken: "allegiantair" },
  { name: "AllTrails", source: "lever", boardToken: "alltrails" },
  { name: "AltaML", source: "lever", boardToken: "altaml" },
  { name: "Analytic Partners", source: "lever", boardToken: "analyticpartners" },
  { name: "Anomali", source: "lever", boardToken: "anomali" },
  { name: "Appen", source: "lever", boardToken: "appen-2" },
  { name: "Aquabyte", source: "lever", boardToken: "aquabyte" },
  { name: "Arc'teryx Equipment", source: "lever", boardToken: "arcteryx.com" },
  { name: "ArteraAI", source: "lever", boardToken: "artera" },
  { name: "Behaviour Interactive", source: "lever", boardToken: "bhvr" },
  { name: "Belvedere Trading", source: "lever", boardToken: "belvederetrading" },
  { name: "BenchSci", source: "lever", boardToken: "benchsci" },
  { name: "Beta Technologies", source: "lever", boardToken: "beta" },
  { name: "BioAgilytix", source: "lever", boardToken: "bioagilytix" },
  { name: "BlueRock Therapeutics", source: "lever", boardToken: "bluerocktx" },
  { name: "Bright Machines", source: "lever", boardToken: "brightmachines" },
  { name: "Brooks Running", source: "lever", boardToken: "brooksrunning" },
  { name: "ButcherBox", source: "lever", boardToken: "butcherbox" },
  { name: "CALSTART", source: "lever", boardToken: "calstart" },
  { name: "Catalist", source: "lever", boardToken: "catalist" },
  { name: "Center for AI Safety", source: "lever", boardToken: "aisafety" },
  { name: "Cirque du Soleil", source: "lever", boardToken: "cirquedusoleil" },
  { name: "CLO Virtual Fashion", source: "lever", boardToken: "clovirtualfashion" },
  { name: "Cloudforce", source: "lever", boardToken: "go-cloudforce" },
  { name: "Coupa Software", source: "lever", boardToken: "coupa" },
  { name: "Crest Industries", source: "lever", boardToken: "crestoperations" },
  { name: "Daniels Health", source: "lever", boardToken: "daniels-sharpsmart" },
  { name: "Democratic Governors Association", source: "lever", boardToken: "dga" },
  { name: "Diversified Automation", source: "lever", boardToken: "diversified-automation" },
  { name: "Drivemode", source: "lever", boardToken: "drivemode" },
  { name: "E-Space", source: "lever", boardToken: "espace" },
  { name: "Ekimetrics", source: "lever", boardToken: "ekimetrics" },
  { name: "Eko Health", source: "lever", boardToken: "ekohealth" },
  { name: "Elf Beauty", source: "lever", boardToken: "elfbeauty" },
  { name: "Elk Valley Resources", source: "lever", boardToken: "evr" },
  { name: "Endpoint Clinical", source: "lever", boardToken: "endpointclinical" },
  { name: "EQ Bank", source: "lever", boardToken: "eqbank" },
  { name: "Equativ", source: "lever", boardToken: "equativ" },
  { name: "EV Realty", source: "lever", boardToken: "evrealty-us" },
  { name: "Exowatt", source: "lever", boardToken: "exowatt" },
  { name: "Extreme Networks", source: "lever", boardToken: "extremenetworks" },
  { name: "Farfetch", source: "lever", boardToken: "farfetch" },
  { name: "Fehr & Peers", source: "lever", boardToken: "fehrandpeers" },
  { name: "Field AI", source: "lever", boardToken: "field-ai" },
  { name: "Firemon", source: "lever", boardToken: "firemon" },
  { name: "Fluxergy", source: "lever", boardToken: "fluxergy-2" },
  { name: "Fullscript", source: "lever", boardToken: "fullscript" },
  { name: "GenBio AI", source: "lever", boardToken: "genbio" },
  { name: "GeoComply", source: "lever", boardToken: "geocomply-2" },
  { name: "GoMaterials", source: "lever", boardToken: "gomaterials" },
  { name: "Gr0", source: "lever", boardToken: "gr0" },
  { name: "Great Gray", source: "lever", boardToken: "great-gray-group" },
  { name: "Greenlight", source: "lever", boardToken: "greenlight" },
  { name: "Hanna Andersson", source: "lever", boardToken: "hannaandersson" },
  { name: "Hermeus", source: "lever", boardToken: "hermeus" },
  { name: "HRL Laboratories", source: "lever", boardToken: "dodmg" },
  { name: "Ibility", source: "lever", boardToken: "ibility" },
  { name: "Ideas United", source: "lever", boardToken: "ideasunited" },
  { name: "IMO Health", source: "lever", boardToken: "imo-online" },
  { name: "Institute of Foundation Models", source: "lever", boardToken: "ifm-us" },
  { name: "Intropic", source: "lever", boardToken: "intropic" },
  { name: "Ivo", source: "lever", boardToken: "ivo" },
  { name: "Kabam", source: "lever", boardToken: "kabam" },
  { name: "Kepler Communications", source: "lever", boardToken: "kepler" },
  { name: "Kpler", source: "lever", boardToken: "kpler" },
  { name: "Larian Studios", source: "lever", boardToken: "larian" },
  { name: "Lendbuzz", source: "lever", boardToken: "lendbuzz" },
  { name: "Level AI", source: "lever", boardToken: "levelai" },
  { name: "Lexeo Therapeutics", source: "lever", boardToken: "lexeotx" },
  { name: "Lightcast", source: "lever", boardToken: "economicmodeling" },
  { name: "Long Wall", source: "lever", boardToken: "longwall" },
  { name: "LTA Research", source: "lever", boardToken: "ltaresearch" },
  { name: "Magnet Forensics", source: "lever", boardToken: "magnetforensics" },
  { name: "Multiply Labs", source: "lever", boardToken: "multiplylabs" },
  { name: "Neighbor", source: "lever", boardToken: "neighbor" },
  { name: "Nextech Systems", source: "lever", boardToken: "nextech" },
  { name: "NextGen Federal Systems", source: "lever", boardToken: "nextgenfed" },
  { name: "Nobull", source: "lever", boardToken: "nobullproject" },
  { name: "Octopus Energy", source: "lever", boardToken: "octoenergy" },
  { name: "Oleria Security", source: "lever", boardToken: "oleria-security" },
  { name: "OpenX", source: "lever", boardToken: "openx" },
  { name: "OraSure Technologies", source: "lever", boardToken: "dnagenotek" },
  { name: "Palantir", source: "lever", boardToken: "palantir" },
  { name: "Parallel Wireless", source: "lever", boardToken: "parallelwireless" },
  { name: "Pelmorex", source: "lever", boardToken: "pelmorex" },
  { name: "Penta Group", source: "lever", boardToken: "pentagrp" },
  { name: "Penumbra Inc", source: "lever", boardToken: "penumbrainc" },
  { name: "PingWind", source: "lever", boardToken: "pingwind" },
  { name: "Pivot Energy", source: "lever", boardToken: "pivotenergy" },
  { name: "Pivotal Software", source: "lever", boardToken: "pivotal" },
  { name: "PlusAI", source: "lever", boardToken: "plus-2" },
  { name: "Prosper Funding", source: "lever", boardToken: "prosper" },
  { name: "Quandri", source: "lever", boardToken: "quandri" },
  { name: "QuantCo", source: "lever", boardToken: "quantco-" },
  { name: "Rainmaker", source: "lever", boardToken: "make-rain" },
  { name: "RAVL", source: "lever", boardToken: "ravl_io" },
  { name: "Redhorse", source: "lever", boardToken: "redhorsecorp" },
  { name: "Redwood Credit Union", source: "lever", boardToken: "redwoodcu" },
  { name: "Reli", source: "lever", boardToken: "shopreli" },
  { name: "Reply", source: "lever", boardToken: "reply" },
  { name: "Rigetti", source: "lever", boardToken: "rigetti" },
  { name: "Robust.ai", source: "lever", boardToken: "robust-ai" },
  { name: "RWS", source: "lever", boardToken: "rws" },
  { name: "Samba TV", source: "lever", boardToken: "sambatv" },
  { name: "Saronic", source: "lever", boardToken: "saronic" },
  { name: "Secureframe", source: "lever", boardToken: "secureframe" },
  { name: "SF Giants", source: "lever", boardToken: "sfgiants" },
  { name: "SFMOMA", source: "lever", boardToken: "sfmoma" },
  { name: "Shield AI", source: "lever", boardToken: "shieldai" },
  { name: "ShyftLabs", source: "lever", boardToken: "shyftlabs" },
  { name: "Skyways", source: "lever", boardToken: "skyways" },
  { name: "SoloPulse", source: "lever", boardToken: "solopulseco" },
  { name: "Spotify", source: "lever", boardToken: "spotify" },
  { name: "Stand Together", source: "lever", boardToken: "standtogether" },
  { name: "SteerBridge", source: "lever", boardToken: "steerbridge" },
  { name: "SunSource", source: "lever", boardToken: "sunsrce" },
  { name: "Sunwater Capital", source: "lever", boardToken: "sunwatercapital" },
  { name: "Syntax", source: "lever", boardToken: "syntax" },
  { name: "Synthego", source: "lever", boardToken: "synthego" },
  { name: "Tahoe Therapeutics", source: "lever", boardToken: "tahoebio-ai" },
  { name: "Tekton", source: "lever", boardToken: "tekton" },
  { name: "Teleo", source: "lever", boardToken: "teleo" },
  { name: "Telesat", source: "lever", boardToken: "telesat" },
  { name: "Telligen", source: "lever", boardToken: "telligen" },
  { name: "The Information Lab", source: "lever", boardToken: "theinformationlab" },
  { name: "Toyota Research Institute", source: "lever", boardToken: "tri" },
  { name: "Traackr", source: "lever", boardToken: "traackr" },
  { name: "UntilLabs", source: "lever", boardToken: "until" },
  { name: "Veeva Systems", source: "lever", boardToken: "veeva" },
  { name: "Very Good Security", source: "lever", boardToken: "verygoodsecurity" },
  { name: "Vevo", source: "lever", boardToken: "vevo" },
  { name: "Vivenu", source: "lever", boardToken: "vivenu" },
  { name: "Voltus", source: "lever", boardToken: "voltus" },
  { name: "Waabi", source: "lever", boardToken: "waabi" },
  { name: "Wade Trim", source: "lever", boardToken: "wadetrim" },
  { name: "Wealthsimple", source: "lever", boardToken: "wealthsimple" },
  { name: "WeRide", source: "lever", boardToken: "weride" },
  { name: "Woven", source: "lever", boardToken: "woven-by-toyota" },
  { name: "Xsolla", source: "lever", boardToken: "xsolla" },
  { name: "zaimler", source: "lever", boardToken: "zaimler" },
  { name: "Zoox", source: "lever", boardToken: "zoox" },
  { name: "Zus Health", source: "lever", boardToken: "zushealth" },
  { name: "1Password", source: "ashby", boardToken: "1password" },
  { name: "1X", source: "ashby", boardToken: "1x" },
  { name: "8VC", source: "ashby", boardToken: "8vc" },
  { name: "Abridge", source: "ashby", boardToken: "abridge" },
  { name: "Abundant", source: "ashby", boardToken: "abundant" },
  { name: "Adaption Labs", source: "ashby", boardToken: "adaption" },
  { name: "Adaptive Security", source: "ashby", boardToken: "adaptivesecurity" },
  { name: "AeroVect", source: "ashby", boardToken: "aerovect" },
  { name: "AfterQuery", source: "ashby", boardToken: "afterquery" },
  { name: "Agentis Capital", source: "ashby", boardToken: "agentis-capital-advisors" },
  { name: "AI Intern to the CEO", source: "ashby", boardToken: "cyvl" },
  { name: "Airspace Intelligence", source: "ashby", boardToken: "airspace-intelligence.com" },
  { name: "Alljoined", source: "ashby", boardToken: "alljoined" },
  { name: "Alloy Enterprises", source: "ashby", boardToken: "alloyenterprises" },
  { name: "ALSO", source: "ashby", boardToken: "ridealso" },
  { name: "Ambrook", source: "ashby", boardToken: "ambrook" },
  { name: "Anterior", source: "ashby", boardToken: "anterior" },
  { name: "Anthelion Capital", source: "ashby", boardToken: "anthelioncap" },
  { name: "Apex", source: "ashby", boardToken: "apex-technology-inc" },
  { name: "Applied Intuition", source: "ashby", boardToken: "applied" },
  { name: "Aptura", source: "ashby", boardToken: "aptura" },
  { name: "Architect Labs", source: "ashby", boardToken: "architect" },
  { name: "Astera", source: "ashby", boardToken: "astera" },
  { name: "Astronomer", source: "ashby", boardToken: "astronomer" },
  { name: "Auctor", source: "ashby", boardToken: "auctor" },
  { name: "Base Power", source: "ashby", boardToken: "base-power" },
  { name: "Baseten", source: "ashby", boardToken: "baseten" },
  { name: "Basis Research Institute", source: "ashby", boardToken: "basis-research" },
  { name: "Beacon Software", source: "ashby", boardToken: "beaconsoftware" },
  { name: "Benchling", source: "ashby", boardToken: "benchling" },
  { name: "Bild AI", source: "ashby", boardToken: "bild-ai" },
  { name: "Binance", source: "ashby", boardToken: "binance.us" },
  { name: "Blackbird Labs", source: "ashby", boardToken: "blackbird-labs-inc" },
  { name: "Blockhouse", source: "ashby", boardToken: "blockhouse" },
  { name: "Bloxd", source: "ashby", boardToken: "bloxd" },
  { name: "Brain Co.", source: "ashby", boardToken: "brainco" },
  { name: "Bree", source: "ashby", boardToken: "bree" },
  { name: "Cartesia", source: "ashby", boardToken: "cartesia" },
  { name: "Centerfield", source: "ashby", boardToken: "centerfield" },
  { name: "Charge Robotics", source: "ashby", boardToken: "charge-robotics" },
  { name: "Circleback", source: "ashby", boardToken: "circleback" },
  { name: "Clera", source: "ashby", boardToken: "clera" },
  { name: "Clipboard Health", source: "ashby", boardToken: "clipboard" },
  { name: "Cohere", source: "ashby", boardToken: "cohere" },
  { name: "Collaborative Robotics", source: "ashby", boardToken: "cobot" },
  { name: "Colonist", source: "ashby", boardToken: "colonist" },
  { name: "Compa", source: "ashby", boardToken: "compa" },
  { name: "Composio", source: "ashby", boardToken: "composio" },
  { name: "Confluent", source: "ashby", boardToken: "confluent" },
  { name: "Constellation Space", source: "ashby", boardToken: "constellationspace" },
  { name: "Context", source: "ashby", boardToken: "context" },
  { name: "Coverdash", source: "ashby", boardToken: "coverdash" },
  { name: "Creatify", source: "ashby", boardToken: "embedding-vc" },
  { name: "Creatify Lab", source: "ashby", boardToken: "creatify" },
  { name: "Crosby", source: "ashby", boardToken: "crosby" },
  { name: "Crusoe", source: "ashby", boardToken: "crusoe" },
  { name: "CTGT", source: "ashby", boardToken: "ctgt" },
  { name: "CuspAI", source: "ashby", boardToken: "cuspai" },
  { name: "Cybernetic Labs", source: "ashby", boardToken: "netic" },
  { name: "d-Matrix", source: "ashby", boardToken: "d-matrix" },
  { name: "Dedalus Labs", source: "ashby", boardToken: "dedalus-labs" },
  { name: "Deepgram", source: "ashby", boardToken: "deepgram" },
  { name: "Delinea", source: "ashby", boardToken: "delinea" },
  { name: "Deliveroo", source: "ashby", boardToken: "deliveroo" },
  { name: "Dexmate", source: "ashby", boardToken: "dexmate" },
  { name: "Ditto", source: "ashby", boardToken: "ditto" },
  { name: "Ditto AI", source: "ashby", boardToken: "dittoai" },
  { name: "Droyd Robotics", source: "ashby", boardToken: "droyd" },
  { name: "Dryft", source: "ashby", boardToken: "dryft" },
  { name: "Egra", source: "ashby", boardToken: "egra" },
  { name: "Eigen Labs", source: "ashby", boardToken: "eigen-labs" },
  { name: "Eight Sleep", source: "ashby", boardToken: "eightsleep" },
  { name: "Ellipsis Labs", source: "ashby", boardToken: "ellipsislabs" },
  { name: "Eloquent AI", source: "ashby", boardToken: "eloquentai" },
  { name: "Epia Neuro", source: "ashby", boardToken: "epianeuro" },
  { name: "Equip Health", source: "ashby", boardToken: "equip" },
  { name: "Eragon", source: "ashby", boardToken: "eragon" },
  { name: "Espa AI", source: "ashby", boardToken: "espa" },
  { name: "Etched", source: "ashby", boardToken: "etched" },
  { name: "ether.fi", source: "ashby", boardToken: "ether.fi" },
  { name: "Exa Labs", source: "ashby", boardToken: "exa" },
  { name: "Eyebot", source: "ashby", boardToken: "eyebot" },
  { name: "Fab2", source: "ashby", boardToken: "fab2" },
  { name: "Faculte", source: "ashby", boardToken: "faculty-fellowship" },
  { name: "Faculty AI", source: "ashby", boardToken: "faculty" },
  { name: "Farsight", source: "ashby", boardToken: "farsight" },
  { name: "Firetiger", source: "ashby", boardToken: "firetiger" },
  { name: "Flagright", source: "ashby", boardToken: "flagright.com" },
  { name: "Fluency", source: "ashby", boardToken: "fluency" },
  { name: "Forus", source: "ashby", boardToken: "forus" },
  { name: "Frontier Health", source: "ashby", boardToken: "frontier-health" },
  { name: "Fundwell", source: "ashby", boardToken: "fundwell" },
  { name: "G2", source: "ashby", boardToken: "g2" },
  { name: "Gamechanger", source: "ashby", boardToken: "gamechanger" },
  { name: "Gecko Robotics", source: "ashby", boardToken: "gecko-robotics" },
  { name: "Gen Digital", source: "ashby", boardToken: "gen-digital" },
  { name: "General Intuition &amp; Medal", source: "ashby", boardToken: "generalintuition-medal" },
  { name: "GenMD", source: "ashby", boardToken: "genmd" },
  { name: "Georgian Partners Growth", source: "ashby", boardToken: "georgian" },
  { name: "Giga AI", source: "ashby", boardToken: "gigaml" },
  { name: "Glimpse Engineering", source: "ashby", boardToken: "glimp-se" },
  { name: "GoLinks", source: "ashby", boardToken: "golinks" },
  { name: "Gorgias", source: "ashby", boardToken: "gorgias" },
  { name: "GrayMatter Robotics", source: "ashby", boardToken: "graymatter-robotics" },
  { name: "Great Question", source: "ashby", boardToken: "greatquestion" },
  { name: "Gritt Robotics Inc", source: "ashby", boardToken: "gritt" },
  { name: "Gumloop", source: "ashby", boardToken: "gumloop" },
  { name: "H3X Technologies", source: "ashby", boardToken: "h3x-technologies" },
  { name: "Hadrian", source: "ashby", boardToken: "hadrian-automation" },
  { name: "Handshake", source: "ashby", boardToken: "handshake" },
  { name: "Harvey", source: "ashby", boardToken: "harvey" },
  { name: "Hawk-Eye Innovations", source: "ashby", boardToken: "hawkeyeinnovations" },
  { name: "Hayden AI", source: "ashby", boardToken: "haydenai" },
  { name: "HCompany", source: "ashby", boardToken: "hcompany" },
  { name: "Heliux", source: "ashby", boardToken: "heliux" },
  { name: "Heron Data", source: "ashby", boardToken: "herondata" },
  { name: "Heron Power", source: "ashby", boardToken: "heron-power" },
  { name: "Higharc", source: "ashby", boardToken: "higharc" },
  { name: "Hiverge", source: "ashby", boardToken: "hiverge" },
  { name: "Homebase", source: "ashby", boardToken: "homebase" },
  { name: "Hubs.is", source: "ashby", boardToken: "hubs.is" },
  { name: "Human Computer Lab", source: "ashby", boardToken: "human-computer-lab" },
  { name: "Hypercubic", source: "ashby", boardToken: "hypercubic" },
  { name: "Illumio", source: "ashby", boardToken: "illumio" },
  { name: "Inherent", source: "ashby", boardToken: "inherent" },
  { name: "Insitro", source: "ashby", boardToken: "insitro" },
  { name: "Internship", source: "ashby", boardToken: "interplay" },
  { name: "Ironclad", source: "ashby", boardToken: "ironcladhq" },
  { name: "Junior AI", source: "ashby", boardToken: "junior" },
  { name: "Juniper Square", source: "ashby", boardToken: "junipersquare" },
  { name: "k-ID", source: "ashby", boardToken: "k-id" },
  { name: "Kastle AI", source: "ashby", boardToken: "kastle" },
  { name: "Keyrock", source: "ashby", boardToken: "keyrock" },
  { name: "Kinetic Systems", source: "ashby", boardToken: "kineticsystems" },
  { name: "Kira", source: "ashby", boardToken: "kira" },
  { name: "Kirin", source: "ashby", boardToken: "kirin" },
  { name: "Kognitos", source: "ashby", boardToken: "kognitos" },
  { name: "Kong", source: "ashby", boardToken: "kong" },
  { name: "kos.ai", source: "ashby", boardToken: "kos.ai" },
  { name: "Lambda", source: "ashby", boardToken: "lambda" },
  { name: "Leland", source: "ashby", boardToken: "leland" },
  { name: "Linear", source: "ashby", boardToken: "linear" },
  { name: "LINQ", source: "ashby", boardToken: "linqapp" },
  { name: "Lovable", source: "ashby", boardToken: "lovable" },
  { name: "Lunon", source: "ashby", boardToken: "lunon" },
  { name: "Lydian", source: "ashby", boardToken: "lydian" },
  { name: "m13", source: "ashby", boardToken: "m13" },
  { name: "Mach Industries", source: "ashby", boardToken: "mach" },
  { name: "Mach9", source: "ashby", boardToken: "mach9" },
  { name: "Mariana Minerals", source: "ashby", boardToken: "marianaminerals" },
  { name: "Matterworks", source: "ashby", boardToken: "matterworks" },
  { name: "Maxima", source: "ashby", boardToken: "maxima" },
  { name: "Maximor AI", source: "ashby", boardToken: "maximor" },
  { name: "Maxinsights", source: "ashby", boardToken: "maxinsights" },
  { name: "Medra", source: "ashby", boardToken: "medraai" },
  { name: "Melius", source: "ashby", boardToken: "melius" },
  { name: "Melotech", source: "ashby", boardToken: "melotech" },
  { name: "Mercor", source: "ashby", boardToken: "mercor" },
  { name: "Meshy", source: "ashby", boardToken: "meshy" },
  { name: "Mistral AI", source: "ashby", boardToken: "mistral.ai" },
  { name: "Modal", source: "ashby", boardToken: "modal" },
  { name: "Monarch Money", source: "ashby", boardToken: "monarchmoney" },
  { name: "Monogram", source: "ashby", boardToken: "monogram" },
  { name: "MUBI", source: "ashby", boardToken: "mubi" },
  { name: "Nash", source: "ashby", boardToken: "nash" },
  { name: "NationGraph", source: "ashby", boardToken: "nationgraph" },
  { name: "Navi AI", source: "ashby", boardToken: "navi" },
  { name: "NeoCognition", source: "ashby", boardToken: "neocognition" },
  { name: "New Lantern", source: "ashby", boardToken: "newlantern" },
  { name: "Niural", source: "ashby", boardToken: "niural" },
  { name: "Normal Computing", source: "ashby", boardToken: "normalcomputing" },
  { name: "NORY", source: "ashby", boardToken: "nory-co" },
  { name: "Notion", source: "ashby", boardToken: "notion" },
  { name: "NOX METALS", source: "ashby", boardToken: "nox-metals" },
  { name: "NTT DATA AIVista", source: "ashby", boardToken: "ntt-data-aivista" },
  { name: "Nuclear Promise X", source: "ashby", boardToken: "npx" },
  { name: "Obvious", source: "ashby", boardToken: "obvious" },
  { name: "Odin Dynamics, Inc", source: "ashby", boardToken: "odin-dynamics" },
  { name: "Odyssey", source: "ashby", boardToken: "odysseyml" },
  { name: "Oligo Space", source: "ashby", boardToken: "oligo" },
  { name: "Ontic", source: "ashby", boardToken: "ontic" },
  { name: "OpenAI", source: "ashby", boardToken: "openai" },
  { name: "OpusClip", source: "ashby", boardToken: "opusclip" },
  { name: "Orbital Industries", source: "ashby", boardToken: "orbitalindustries" },
  { name: "Osmo", source: "ashby", boardToken: "osmo" },
  { name: "Outmarket AI", source: "ashby", boardToken: "outmarket" },
  { name: "Outpost Technologies", source: "ashby", boardToken: "outpostnow" },
  { name: "Output Biosciences", source: "ashby", boardToken: "output" },
  { name: "Overview Energy", source: "ashby", boardToken: "overviewenergy" },
  { name: "Parallel Web Systems", source: "ashby", boardToken: "parallel" },
  { name: "Parspec", source: "ashby", boardToken: "parspec" },
  { name: "Patreon", source: "ashby", boardToken: "patreon" },
  { name: "Pebl", source: "ashby", boardToken: "pebl" },
  { name: "Perchwell", source: "ashby", boardToken: "perchwell" },
  { name: "Periodic Labs", source: "ashby", boardToken: "periodic-labs" },
  { name: "Perplexity AI", source: "ashby", boardToken: "perplexity" },
  { name: "Persona", source: "ashby", boardToken: "persona" },
  { name: "Persona AI", source: "ashby", boardToken: "persona.ai" },
  { name: "Phia", source: "ashby", boardToken: "phia" },
  { name: "Phil", source: "ashby", boardToken: "phil" },
  { name: "Phlair", source: "ashby", boardToken: "phlair" },
  { name: "Phoebe", source: "ashby", boardToken: "phoebe-work" },
  { name: "Phonely", source: "ashby", boardToken: "phonely" },
  { name: "Phonic", source: "ashby", boardToken: "phonic" },
  { name: "Physical Intelligence", source: "ashby", boardToken: "physicalintelligence" },
  { name: "Pika", source: "ashby", boardToken: "pika" },
  { name: "Pivot Robotics", source: "ashby", boardToken: "pivotrobotics" },
  { name: "Polymath", source: "ashby", boardToken: "polymath" },
  { name: "Poshmark", source: "ashby", boardToken: "poshmark" },
  { name: "Prime Intellect", source: "ashby", boardToken: "primeintellect" },
  { name: "Prior Labs", source: "ashby", boardToken: "prior-labs" },
  { name: "Proxima", source: "ashby", boardToken: "proxima" },
  { name: "Pylon", source: "ashby", boardToken: "pylon-labs" },
  { name: "Quadrillion", source: "ashby", boardToken: "quadrillion-labs" },
  { name: "Ramp", source: "ashby", boardToken: "ramp" },
  { name: "RapDev", source: "ashby", boardToken: "rapdev" },
  { name: "Reality Defender", source: "ashby", boardToken: "realitydefender" },
  { name: "Realm", source: "ashby", boardToken: "realmalliance" },
  { name: "Reflect Orbital", source: "ashby", boardToken: "reflect-orbital" },
  { name: "Relay Financial", source: "ashby", boardToken: "relayfi" },
  { name: "Remarcable", source: "ashby", boardToken: "remarcable-inc" },
  { name: "Replit", source: "ashby", boardToken: "replit" },
  { name: "Revise Robotics", source: "ashby", boardToken: "reviserobotics" },
  { name: "Rho", source: "ashby", boardToken: "rho" },
  { name: "Riveron", source: "ashby", boardToken: "riveron" },
  { name: "Rivet Industries", source: "ashby", boardToken: "rivet" },
  { name: "Rivian and Volkswagen Group Technologies", source: "ashby", boardToken: "rivianvw.tech" },
  { name: "Roam", source: "ashby", boardToken: "tryroam" },
  { name: "Rocket Science Group", source: "ashby", boardToken: "rocketsciencegg" },
  { name: "Root Access", source: "ashby", boardToken: "root-access" },
  { name: "Rundoo", source: "ashby", boardToken: "rundoo" },
  { name: "SandboxAQ", source: "ashby", boardToken: "sandboxaq" },
  { name: "Saronic", source: "ashby", boardToken: "saronic" },
  { name: "Sentra", source: "ashby", boardToken: "sentra" },
  { name: "Sentry", source: "ashby", boardToken: "sentry" },
  { name: "Sereact", source: "ashby", boardToken: "sereact" },
  { name: "Serval", source: "ashby", boardToken: "serval" },
  { name: "Sierra", source: "ashby", boardToken: "sierra" },
  { name: "Sieve", source: "ashby", boardToken: "sieve" },
  { name: "Skydio", source: "ashby", boardToken: "skydio" },
  { name: "Snowflake", source: "ashby", boardToken: "snowflake" },
  { name: "Socket", source: "ashby", boardToken: "socket" },
  { name: "Socure", source: "ashby", boardToken: "socure" },
  { name: "Solink", source: "ashby", boardToken: "solink" },
  { name: "Spacial AI", source: "ashby", boardToken: "spacial" },
  { name: "Span", source: "ashby", boardToken: "span" },
  { name: "Stand Insurance", source: "ashby", boardToken: "standinsurance" },
  { name: "Super", source: "ashby", boardToken: "super.com" },
  { name: "Sweatpals", source: "ashby", boardToken: "sweatpals" },
  { name: "Taara", source: "ashby", boardToken: "taaraconnect" },
  { name: "Tacit", source: "ashby", boardToken: "tacit" },
  { name: "Tempo", source: "ashby", boardToken: "tempo-io" },
  { name: "TensorWave", source: "ashby", boardToken: "tensorwave" },
  { name: "Terminal", source: "ashby", boardToken: "terminal" },
  { name: "Terranova", source: "ashby", boardToken: "terranova" },
  { name: "Tessera Labs", source: "ashby", boardToken: "tessera-labs" },
  { name: "The Voleon Group", source: "ashby", boardToken: "voleon" },
  { name: "Tilde Research", source: "ashby", boardToken: "tilderesearch" },
  { name: "tldraw", source: "ashby", boardToken: "tldraw" },
  { name: "Tonal", source: "ashby", boardToken: "tonal" },
  { name: "Treefera", source: "ashby", boardToken: "treefera" },
  { name: "Triumph", source: "ashby", boardToken: "triumph-arcade" },
  { name: "Turion Space", source: "ashby", boardToken: "turion-space" },
  { name: "UiPath", source: "ashby", boardToken: "uipath" },
  { name: "Uncountable", source: "ashby", boardToken: "uncountable" },
  { name: "Unify", source: "ashby", boardToken: "unify" },
  { name: "Unlikely AI", source: "ashby", boardToken: "unlikelyai" },
  { name: "Unwrap", source: "ashby", boardToken: "unwrap" },
  { name: "Upvest", source: "ashby", boardToken: "upvest" },
  { name: "Valstad", source: "ashby", boardToken: "valstad" },
  { name: "Vantage", source: "ashby", boardToken: "vantage" },
  { name: "Varick Agents", source: "ashby", boardToken: "varick-agents" },
  { name: "Veeda AI", source: "ashby", boardToken: "veeda-labs" },
  { name: "Vega Investment Technologies", source: "ashby", boardToken: "vega" },
  { name: "Vendelux", source: "ashby", boardToken: "vendelux" },
  { name: "Vital Lyfe", source: "ashby", boardToken: "vital-lyfe" },
  { name: "Vmax AI Corp", source: "ashby", boardToken: "vmax" },
  { name: "Voldex", source: "ashby", boardToken: "voldex" },
  { name: "Wealth.com", source: "ashby", boardToken: "wealth-com" },
  { name: "Wealthsimple", source: "ashby", boardToken: "wealthsimple" },
  { name: "Weave", source: "ashby", boardToken: "weave" },
  { name: "WebAI", source: "ashby", boardToken: "webai" },
  { name: "WindBorne Systems", source: "ashby", boardToken: "windborne-systems" },
  { name: "Worldly", source: "ashby", boardToken: "worldly" },
  { name: "Yotta Labs", source: "ashby", boardToken: "yotta" },
  { name: "Zello", source: "ashby", boardToken: "zello" },
  { name: "Zettabyte", source: "ashby", boardToken: "zettabyte-space" },
  { name: "Zip", source: "ashby", boardToken: "zip" },
  { name: "Zuru", source: "ashby", boardToken: "zuru" },
];
